// Built-in catalog of services.
//
// type (required):
//   "algolia"      — Algolia custom API; polls /3/public/availability.
//   "auth0"        — Auth0 custom Next.js page; extracts buildId from HTML then
//                    fetches /_next/data/{buildId}/index.json for region status.
//   "awshealth"    — AWS Service Health Dashboard; polls /public/currentevents (UTF-16 encoded).
//   "cachet"       — CachetHQ status pages; polls /components and /incidents. Supports both
//   "checkly"      — Checkly (checklyhq.com) status pages; derives component status from
//                    /api/status-page/{slug}/unresolved-incidents and uptime. Requires a
//                    `slug` field on the catalog entry.
//                    v1/v2 flat format and v3 JSON:API format (auto-detected per response).
//   "google"       — Google incident dashboard format (used by Google Workspace and Google Cloud);
//                    polls /incidents.json + /products.json and derives status from active incidents
//                    (those with no `end` field).
//   "heroku"       — Heroku custom API; polls /api/v4/current-status.
//   "hund"         — Hund.io status pages; reads the first SSE init_event from /live/v2/status_page.
//   "incidentio"   — incident.io status pages; exposes the same /api/v2 endpoints as Statuspage.io,
//                    so the same fetcher handles both.
//   "instatus"     — Instatus-hosted status pages; polls /api/v2/summary.json and
//                    /api/v2/components.json. No public incidents endpoint available.
//   "pagerduty"    — PagerDuty status page product; polls /api/services and /api/posts.
//   "posthog"      — PostHog custom Next.js status page; polls /api/status.
//   "signal"       — Signal's hand-rolled HTML page; no API. Scrapes text for "up and running".
//                    Beta — fragile if Signal changes their wording.
//   "site24x7"     — StatusIQ (Zoho/Site24x7); polls /sp/api/u/summary_details.
//   "slack"        — Slack's custom status API at /api/v1.0.0/current.
//   "sorryapp"     — SorryApp platform; polls /api/v1/status, /api/v1/components, /api/v1/notices.
//   "statuscast"   — StatusCast platform; polls /status.json, /components.json, /incidents.json.
//                    Requires a browser User-Agent (bot filter).
//   "statusio"     — status.io pages; single endpoint at api.status.io/1.0/status/{pageId}.
//                    Requires a `pageId` field on the catalog entry.
//   "statuspage"   — Atlassian Statuspage.io, uses /api/v2 endpoints.
//   "stripe"       — Stripe custom status page; polls /current/full.
//   "uptimerobot"  — UptimeRobot status pages; uses /api/getMonitorList/x.
//   "zendesk"      — Zendesk custom JSON:API; polls /api/ssp/services.json and
//                    /api/ssp/incidents.json?as_of_date={date}.
//
// searchAliases: additional keywords matched when the user types in the catalog search box.
//   Use this for well-known product names that aren't part of the service name
//   (e.g. "jira", "gmail", "chatgpt"). All lowercase; matched as substrings.
//
// relatedDomains: product/app domains for this service.
//   Patterns starting with "*." match that domain and all its subdomains.
//   Used to suggest adding a service when the user visits a related page
//   (e.g. visiting claude.ai suggests tracking status.claude.com).
//
// Intentionally excluded from wildcards: user-content hosts such as
//   *.github.io, *.vercel.app, *.netlify.app, *.myshopify.com, *.onrender.com
const CATALOG = {
  '100ms': {
    name: '100ms',
    type: 'statuspage',
    websiteUrl: 'https://100ms.live',
    statusPageUrl: 'https://status.100ms.live',
    relatedDomains: ['100ms.live', '*.100ms.live'],
    searchAliases: ['video', 'webrtc', 'live'],
  },
  '1password': {
    name: '1Password',
    type: 'statuspage',
    websiteUrl: 'https://1password.com',
    statusPageUrl: 'https://status.1password.com',
    relatedDomains: ['1password.com', '*.1password.com'],
    searchAliases: ['password manager', 'secrets', 'vault', 'security'],
  },
  'ably': {
    name: 'Ably',
    type: 'statuspage',
    websiteUrl: 'https://ably.com',
    statusPageUrl: 'https://status.ably.com',
    relatedDomains: ['ably.com', '*.ably.com', 'ably.io', '*.ably.io'],
    searchAliases: ['realtime', 'websocket', 'pubsub', 'messaging', 'push notifications'],
  },
  'ai21': {
    name: 'AI21 Labs',
    type: 'statuspage',
    websiteUrl: 'https://ai21.com',
    statusPageUrl: 'https://status.ai21.com',
    relatedDomains: ['ai21.com', '*.ai21.com'],
    searchAliases: ['llm', 'ai', 'jurassic'],
  },
  'airbyte': {
    name: 'Airbyte',
    type: 'instatus',
    websiteUrl: 'https://airbyte.com',
    statusPageUrl: 'https://status.airbyte.com',
    relatedDomains: ['airbyte.com', '*.airbyte.com'],
    searchAliases: ['etl', 'data pipeline', 'data integration', 'connector', 'sync'],
  },
  'airtable': {
    name: 'Airtable',
    type: 'statuspage',
    websiteUrl: 'https://airtable.com',
    statusPageUrl: 'https://status.airtable.com',
    relatedDomains: ['airtable.com', '*.airtable.com'],
    searchAliases: ['database', 'spreadsheet', 'no-code', 'base', 'grid'],
  },
  'aiven': {
    name: 'Aiven',
    type: 'statuspage',
    websiteUrl: 'https://aiven.io',
    statusPageUrl: 'https://status.aiven.io',
    relatedDomains: ['aiven.io', '*.aiven.io'],
    searchAliases: ['managed database', 'kafka', 'postgres'],
  },
  'alchemy': {
    name: 'Alchemy',
    type: 'statuspage',
    websiteUrl: 'https://alchemy.com',
    statusPageUrl: 'https://status.alchemy.com',
    relatedDomains: ['alchemy.com', '*.alchemy.com'],
    searchAliases: ['web3', 'blockchain', 'ethereum', 'polygon', 'solana', 'nft', 'smart contracts', 'rpc'],
  },
  'algolia': {
    name: 'Algolia',
    type: 'algolia',
    websiteUrl: 'https://algolia.com',
    statusPageUrl: 'https://status.algolia.com',
    relatedDomains: ['algolia.com', '*.algolia.com', 'algolia.net', '*.algolia.net'],
    searchAliases: ['search', 'autocomplete', 'instant search', 'indexing'],
  },
  'amplitude': {
    name: 'Amplitude',
    type: 'statuspage',
    websiteUrl: 'https://amplitude.com',
    statusPageUrl: 'https://status.amplitude.com',
    relatedDomains: ['amplitude.com', '*.amplitude.com'],
    searchAliases: ['analytics', 'product analytics', 'events'],
  },
  'apify': {
    name: 'Apify',
    type: 'statuspage',
    websiteUrl: 'https://apify.com',
    statusPageUrl: 'https://status.apify.com',
    relatedDomains: ['apify.com', '*.apify.com'],
    searchAliases: ['scraping', 'web scraper', 'crawler', 'automation', 'actor', 'proxy'],
  },
  'apivideo': {
    name: 'api.video',
    type: 'statuspage',
    websiteUrl: 'https://api.video',
    statusPageUrl: 'https://status.api.video',
    relatedDomains: ['api.video', '*.api.video'],
    searchAliases: ['video', 'streaming', 'api'],
  },
  'asana': {
    name: 'Asana',
    type: 'statuspage',
    websiteUrl: 'https://asana.com',
    statusPageUrl: 'https://status.asana.com',
    relatedDomains: ['asana.com', '*.asana.com'],
    searchAliases: ['project management', 'tasks', 'work'],
  },
  'assemblyai': {
    name: 'AssemblyAI',
    type: 'statuspage',
    websiteUrl: 'https://assemblyai.com',
    statusPageUrl: 'https://status.assemblyai.com',
    relatedDomains: ['assemblyai.com', '*.assemblyai.com'],
    searchAliases: ['speech to text', 'transcription', 'ai'],
  },
  'atlassian': {
    name: 'Atlassian',
    type: 'statuspage',
    websiteUrl: 'https://atlassian.com',
    statusPageUrl: 'https://status.atlassian.com',
    relatedDomains: [
      'atlassian.com', '*.atlassian.com',
      'atlassian.net', '*.atlassian.net',
      'jira.com', '*.jira.com',
      'trello.com', '*.trello.com',
      'confluence.com',
    ],
    searchAliases: ['jira', 'confluence', 'trello', 'bitbucket', 'opsgenie', 'statuspage', 'loom', 'issues', 'project management'],
  },
  'auth0': {
    name: 'Auth0',
    type: 'auth0',
    websiteUrl: 'https://auth0.com',
    statusPageUrl: 'https://status.auth0.com',
    relatedDomains: ['auth0.com', '*.auth0.com', 'okta.com', '*.okta.com'],
    searchAliases: ['okta', 'authentication', 'identity', 'login', 'sso', 'oauth'],
  },
  'aws': {
    name: 'AWS',
    type: 'awshealth',
    beta: true,
    websiteUrl: 'https://aws.amazon.com',
    statusPageUrl: 'https://health.aws.com/health/status',
    relatedDomains: ['aws.amazon.com', 'console.aws.amazon.com', 'health.aws.com'],
    searchAliases: ['amazon', 'amazon web services', 'ec2', 's3', 'lambda', 'rds', 'cloudfront', 'dynamodb', 'eks', 'ecs', 'cloudwatch'],
  },
  'axiom': {
    name: 'Axiom',
    type: 'statuspage',
    websiteUrl: 'https://axiom.co',
    statusPageUrl: 'https://axiomdev.statuspage.io',
    relatedDomains: ['axiom.co', '*.axiom.co'],
    searchAliases: ['logs', 'log analytics', 'observability', 'tracing', 'events', 'monitoring'],
  },
  'bandwidth': {
    name: 'Bandwidth',
    type: 'statuspage',
    websiteUrl: 'https://bandwidth.com',
    statusPageUrl: 'https://status.bandwidth.com',
    relatedDomains: ['bandwidth.com', '*.bandwidth.com'],
    searchAliases: ['sms', 'voice', 'telephony'],
  },
  'baseten': {
    name: 'Baseten',
    type: 'statuspage',
    websiteUrl: 'https://baseten.co',
    statusPageUrl: 'https://status.baseten.co',
    relatedDomains: ['baseten.co', '*.baseten.co'],
    searchAliases: ['inference', 'ml', 'deploy', 'ai'],
  },
  'bigcommerce': {
    name: 'BigCommerce',
    type: 'statuspage',
    websiteUrl: 'https://bigcommerce.com',
    statusPageUrl: 'https://status.bigcommerce.com',
    relatedDomains: ['bigcommerce.com', '*.bigcommerce.com'],
    searchAliases: ['ecommerce', 'store', 'cart'],
  },
  'bitbucket': {
    name: 'Bitbucket',
    type: 'statuspage',
    websiteUrl: 'https://bitbucket.org',
    statusPageUrl: 'https://bitbucket.status.atlassian.com',
    relatedDomains: ['bitbucket.org', '*.bitbucket.org'],
    searchAliases: ['git', 'repository', 'pipelines', 'source control'],
  },
  'bitmovin': {
    name: 'Bitmovin',
    type: 'instatus',
    websiteUrl: 'https://bitmovin.com',
    statusPageUrl: 'https://status.bitmovin.com',
    relatedDomains: ['bitmovin.com', '*.bitmovin.com'],
    searchAliases: ['video', 'encoding', 'player'],
  },
  'bitrise': {
    name: 'Bitrise',
    type: 'statuspage',
    websiteUrl: 'https://bitrise.io',
    statusPageUrl: 'https://status.bitrise.io',
    relatedDomains: ['bitrise.io', '*.bitrise.io'],
    searchAliases: ['ci', 'mobile', 'build'],
  },
  'bitwarden': {
    name: 'Bitwarden',
    type: 'hund',
    websiteUrl: 'https://bitwarden.com',
    statusPageUrl: 'https://status.bitwarden.com',
    relatedDomains: ['bitwarden.com', '*.bitwarden.com'],
    searchAliases: ['password manager', 'passwords', 'vault', 'security'],
  },
  'box': {
    name: 'Box',
    type: 'statuspage',
    websiteUrl: 'https://box.com',
    statusPageUrl: 'https://status.box.com',
    relatedDomains: ['box.com', '*.box.com'],
    searchAliases: ['storage', 'files', 'cloud storage'],
  },
  'braintrust': {
    name: 'Braintrust',
    type: 'statuspage',
    websiteUrl: 'https://braintrust.dev',
    statusPageUrl: 'https://status.braintrust.dev',
    relatedDomains: ['braintrust.dev', '*.braintrust.dev'],
    searchAliases: ['llm evals', 'observability', 'ai'],
  },
  'braze': {
    name: 'Braze',
    type: 'statuspage',
    websiteUrl: 'https://braze.com',
    statusPageUrl: 'https://status.braze.com',
    relatedDomains: ['braze.com', '*.braze.com'],
    searchAliases: ['customer engagement', 'messaging', 'crm'],
  },
  'brevo': {
    name: 'Brevo',
    type: 'statuspage',
    websiteUrl: 'https://brevo.com',
    statusPageUrl: 'https://status.brevo.com',
    relatedDomains: ['brevo.com', '*.brevo.com', 'sendinblue.com', '*.sendinblue.com'],
    searchAliases: ['email', 'sendinblue', 'marketing', 'sms'],
  },
  'brex': {
    name: 'Brex',
    type: 'statuspage',
    websiteUrl: 'https://brex.com',
    statusPageUrl: 'https://status.brex.com',
    relatedDomains: ['brex.com', '*.brex.com'],
    searchAliases: ['fintech', 'corporate card', 'spend management', 'banking', 'finance'],
  },
  'browserbase': {
    name: 'Browserbase',
    type: 'statuspage',
    websiteUrl: 'https://browserbase.com',
    statusPageUrl: 'https://status.browserbase.com',
    relatedDomains: ['browserbase.com', '*.browserbase.com'],
    searchAliases: ['headless browser', 'automation', 'ai agents'],
  },
  'bugsnag': {
    name: 'BugSnag',
    type: 'statuspage',
    websiteUrl: 'https://bugsnag.com',
    statusPageUrl: 'https://bugsnag.status.smartbear.com',
    relatedDomains: ['bugsnag.com', '*.bugsnag.com', 'smartbear.com', '*.smartbear.com'],
    searchAliases: ['error tracking', 'crash reporting', 'monitoring'],
  },
  'buildkite': {
    name: 'Buildkite',
    type: 'statuspage',
    websiteUrl: 'https://buildkite.com',
    statusPageUrl: 'https://www.buildkitestatus.com',
    relatedDomains: ['buildkite.com', '*.buildkite.com'],
    searchAliases: ['ci', 'cd', 'ci/cd', 'continuous integration', 'pipeline', 'build', 'agents'],
  },
  'bunny': {
    name: 'Bunny.net',
    type: 'statuspage',
    websiteUrl: 'https://bunny.net',
    statusPageUrl: 'https://status.bunny.net',
    relatedDomains: ['bunny.net', '*.bunny.net'],
    searchAliases: ['cdn', 'edge', 'storage'],
  },
  'canva': {
    name: 'Canva',
    type: 'statuspage',
    websiteUrl: 'https://canva.com',
    statusPageUrl: 'https://www.canvastatus.com',
    relatedDomains: ['canva.com', '*.canva.com'],
    searchAliases: ['design', 'graphics', 'templates'],
  },
  'cerebras': {
    name: 'Cerebras',
    type: 'statuspage',
    websiteUrl: 'https://cerebras.ai',
    statusPageUrl: 'https://status.cerebras.ai',
    relatedDomains: ['cerebras.ai', '*.cerebras.ai'],
    searchAliases: ['inference', 'llm', 'ai', 'chips'],
  },
  'chargebee': {
    name: 'Chargebee',
    type: 'statuspage',
    websiteUrl: 'https://chargebee.com',
    statusPageUrl: 'https://status.chargebee.com',
    relatedDomains: ['chargebee.com', '*.chargebee.com'],
    searchAliases: ['billing', 'subscriptions', 'revenue'],
  },
  'chroma': {
    name: 'Chroma',
    type: 'instatus',
    websiteUrl: 'https://trychroma.com',
    statusPageUrl: 'https://status.trychroma.com',
    relatedDomains: ['trychroma.com', '*.trychroma.com', 'chromadb.com', '*.chromadb.com'],
    searchAliases: ['vector database', 'embeddings', 'ai'],
  },
  'circleci': {
    name: 'CircleCI',
    type: 'statuspage',
    websiteUrl: 'https://circleci.com',
    statusPageUrl: 'https://status.circleci.com',
    relatedDomains: ['circleci.com', '*.circleci.com'],
    searchAliases: ['ci', 'cd', 'ci/cd', 'continuous integration', 'pipeline', 'build'],
  },
  'claude': {
    name: 'Claude',
    type: 'statuspage',
    websiteUrl: 'https://claude.ai',
    statusPageUrl: 'https://status.claude.com',
    relatedDomains: ['claude.ai', '*.claude.ai', 'anthropic.com', '*.anthropic.com'],
    searchAliases: ['anthropic', 'ai', 'llm', 'chatbot'],
  },
  'clerk': {
    name: 'Clerk',
    type: 'statuspage',
    websiteUrl: 'https://clerk.com',
    statusPageUrl: 'https://status.clerk.com',
    relatedDomains: ['clerk.com', '*.clerk.com', 'clerk.dev', '*.clerk.dev', 'clerk.accounts.dev'],
    searchAliases: ['authentication', 'auth', 'login', 'user management', 'identity', 'session'],
  },
  'clever-cloud': {
    name: 'Clever Cloud',
    type: 'cachet',
    beta: true,
    websiteUrl: 'https://clever-cloud.com',
    statusPageUrl: 'https://www.clevercloudstatus.com',
    relatedDomains: ['clever-cloud.com', '*.clever-cloud.com'],
    searchAliases: ['paas', 'cloud', 'hosting', 'deployment', 'scaleway'],
  },
  'clickhouse': {
    name: 'ClickHouse',
    type: 'statuspage',
    websiteUrl: 'https://clickhouse.com',
    statusPageUrl: 'https://status.clickhouse.com',
    relatedDomains: ['clickhouse.com', '*.clickhouse.com'],
    searchAliases: ['olap', 'analytics', 'database', 'columnar'],
  },
  'cloudflare': {
    name: 'Cloudflare',
    type: 'statuspage',
    websiteUrl: 'https://cloudflare.com',
    statusPageUrl: 'https://www.cloudflarestatus.com',
    relatedDomains: ['cloudflare.com', '*.cloudflare.com'],
    searchAliases: ['cdn', 'dns', 'workers', 'pages', 'waf', 'ddos', 'tunnel', 'r2'],
  },
  'cloudinary': {
    name: 'Cloudinary',
    type: 'statuspage',
    websiteUrl: 'https://cloudinary.com',
    statusPageUrl: 'https://status.cloudinary.com',
    relatedDomains: ['cloudinary.com', '*.cloudinary.com'],
    searchAliases: ['images', 'media', 'cdn', 'video', 'image optimization', 'upload'],
  },
  'cloudsmith': {
    name: 'Cloudsmith',
    type: 'statuspage',
    websiteUrl: 'https://cloudsmith.com',
    statusPageUrl: 'https://status.cloudsmith.com',
    relatedDomains: ['cloudsmith.com', '*.cloudsmith.com', 'cloudsmith.io', '*.cloudsmith.io'],
    searchAliases: ['package registry', 'artifact', 'npm', 'docker', 'maven', 'pypi', 'repository'],
  },
  'cockroachdb': {
    name: 'CockroachDB',
    type: 'statuspage',
    websiteUrl: 'https://cockroachlabs.com',
    statusPageUrl: 'https://status.cockroachlabs.cloud',
    relatedDomains: ['cockroachlabs.com', '*.cockroachlabs.com'],
    searchAliases: ['database', 'distributed sql', 'postgres'],
  },
  // relatedDomains[0] is the favicon lookup key: the CDN has no icon for
  // codecov.io or codecov.com, only for the landing host they redirect to.
  'coda': {
    name: 'Coda',
    type: 'statuspage',
    websiteUrl: 'https://coda.io',
    statusPageUrl: 'https://status.coda.io',
    relatedDomains: ['coda.io', '*.coda.io'],
    searchAliases: ['docs', 'tables', 'collaboration'],
  },
  'codecov': {
    name: 'Codecov',
    type: 'statuspage',
    websiteUrl: 'https://codecov.io',
    statusPageUrl: 'https://status.codecov.com',
    relatedDomains: ['about.codecov.io', 'codecov.io', '*.codecov.io', 'codecov.com', '*.codecov.com'],
    searchAliases: ['coverage', 'testing', 'ci'],
  },
  'coderabbit': {
    name: 'CodeRabbit',
    type: 'instatus',
    websiteUrl: 'https://coderabbit.ai',
    statusPageUrl: 'https://status.coderabbit.ai',
    relatedDomains: ['coderabbit.ai', '*.coderabbit.ai'],
    searchAliases: ['code review', 'ai', 'pull requests'],
  },
  'cohere': {
    name: 'Cohere',
    type: 'statuspage',
    websiteUrl: 'https://cohere.com',
    statusPageUrl: 'https://status.cohere.com',
    relatedDomains: ['cohere.com', '*.cohere.com', 'cohere.ai', '*.cohere.ai'],
    searchAliases: ['ai', 'llm', 'nlp', 'embeddings', 'language model', 'text generation'],
  },
  'configcat': {
    name: 'ConfigCat',
    type: 'site24x7',
    websiteUrl: 'https://configcat.com',
    statusPageUrl: 'https://status.configcat.com',
    relatedDomains: ['configcat.com', '*.configcat.com'],
    searchAliases: ['feature flags', 'feature toggles', 'feature management', 'a/b testing'],
  },
  'confluence': {
    name: 'Confluence',
    type: 'statuspage',
    websiteUrl: 'https://atlassian.com/software/confluence',
    statusPageUrl: 'https://confluence.status.atlassian.com',
    relatedDomains: ['atlassian.net', '*.atlassian.net', 'confluence.com'],
    searchAliases: ['wiki', 'docs', 'atlassian'],
  },
  'confluent': {
    name: 'Confluent',
    type: 'statuspage',
    websiteUrl: 'https://confluent.io',
    statusPageUrl: 'https://status.confluent.cloud',
    relatedDomains: ['confluent.io', '*.confluent.io'],
    searchAliases: ['kafka', 'streaming', 'events'],
  },
  'contentful': {
    name: 'Contentful',
    type: 'statuspage',
    websiteUrl: 'https://contentful.com',
    statusPageUrl: 'https://www.contentfulstatus.com',
    relatedDomains: ['contentful.com', '*.contentful.com'],
    searchAliases: ['cms', 'headless cms', 'content management', 'content api', 'rich text'],
  },
  'convex': {
    name: 'Convex',
    type: 'statuspage',
    websiteUrl: 'https://convex.dev',
    statusPageUrl: 'https://status.convex.dev',
    relatedDomains: ['convex.dev', '*.convex.dev'],
    searchAliases: ['database', 'backend', 'reactive'],
  },
  'courier': {
    name: 'Courier',
    type: 'statuspage',
    websiteUrl: 'https://courier.com',
    statusPageUrl: 'https://status.courier.com',
    relatedDomains: ['courier.com', '*.courier.com', 'trycourier.com', '*.trycourier.com'],
    searchAliases: ['notifications', 'email', 'sms', 'push', 'in-app', 'messaging'],
  },
  'cratesio': {
    name: 'crates.io',
    type: 'statuspage',
    websiteUrl: 'https://crates.io',
    statusPageUrl: 'https://status.crates.io',
    relatedDomains: ['crates.io', '*.crates.io', 'docs.rs'],
    searchAliases: ['rust', 'packages', 'registry', 'cargo'],
  },
  'cursor': {
    name: 'Cursor',
    type: 'statuspage',
    websiteUrl: 'https://cursor.com',
    statusPageUrl: 'https://status.cursor.com',
    relatedDomains: ['cursor.com', '*.cursor.com'],
    searchAliases: ['ide', 'code editor', 'ai coding', 'copilot'],
  },
  'customerio': {
    name: 'Customer.io',
    type: 'statuspage',
    websiteUrl: 'https://customer.io',
    statusPageUrl: 'https://customerio.statuspage.io',
    relatedDomains: ['customer.io', '*.customer.io'],
    searchAliases: ['email', 'automation', 'messaging'],
  },
  'daily': {
    name: 'Daily',
    type: 'statuspage',
    websiteUrl: 'https://daily.co',
    statusPageUrl: 'https://status.daily.co',
    relatedDomains: ['daily.co', '*.daily.co'],
    searchAliases: ['video', 'webrtc', 'calls'],
  },
  'dashdoc': {
    name: 'Dashdoc',
    type: 'incidentio',
    websiteUrl: 'https://dashdoc.eu',
    statusPageUrl: 'https://www.dashdocstatus.com',
    relatedDomains: ['dashdoc.eu', '*.dashdoc.eu', 'dashdoc.com', '*.dashdoc.com'],
    searchAliases: ['transport', 'tms', 'logistics', 'freight', 'trucking'],
  },
  'dashlane': {
    name: 'Dashlane',
    type: 'statusio',
    websiteUrl: 'https://dashlane.com',
    statusPageUrl: 'https://status.dashlane.com',
    pageId:  '5aabcb89fccc4b04d3774443',
    relatedDomains: ['dashlane.com', '*.dashlane.com'],
    searchAliases: ['password manager', 'passwords', 'vault', 'security'],
  },
  'datadog': {
    name: 'Datadog',
    type: 'statuspage',
    websiteUrl: 'https://datadoghq.com',
    statusPageUrl: 'https://status.datadoghq.com',
    relatedDomains: ['datadoghq.com', '*.datadoghq.com'],
    searchAliases: ['monitoring', 'apm', 'logs', 'observability', 'metrics', 'infrastructure'],
  },
  'dbtlabs': {
    name: 'dbt Labs',
    type: 'statuspage',
    websiteUrl: 'https://getdbt.com',
    statusPageUrl: 'https://status.getdbt.com',
    relatedDomains: ['getdbt.com', '*.getdbt.com', 'dbtlabs.com', '*.dbtlabs.com'],
    searchAliases: ['analytics engineering', 'transform', 'elt'],
  },
  'deepgram': {
    name: 'Deepgram',
    type: 'statuspage',
    websiteUrl: 'https://deepgram.com',
    statusPageUrl: 'https://status.deepgram.com',
    relatedDomains: ['deepgram.com', '*.deepgram.com'],
    searchAliases: ['speech to text', 'transcription', 'ai'],
  },
  'deno': {
    name: 'Deno',
    type: 'instatus',
    websiteUrl: 'https://deno.com',
    statusPageUrl: 'https://denostatus.com',
    relatedDomains: ['deno.com', '*.deno.com', 'deno.land', '*.deno.land', 'deno.dev', '*.deno.dev'],
    searchAliases: ['javascript', 'typescript', 'runtime', 'deploy', 'edge', 'serverless'],
  },
  'depot': {
    name: 'Depot',
    type: 'statuspage',
    websiteUrl: 'https://depot.dev',
    statusPageUrl: 'https://status.depot.dev',
    relatedDomains: ['depot.dev', '*.depot.dev'],
    searchAliases: ['build', 'ci', 'docker', 'cache'],
  },
  'digitalocean': {
    name: 'DigitalOcean',
    type: 'statuspage',
    websiteUrl: 'https://digitalocean.com',
    statusPageUrl: 'https://status.digitalocean.com',
    relatedDomains: ['digitalocean.com', '*.digitalocean.com'],
    searchAliases: ['cloud', 'droplet', 'vps', 'kubernetes', 'spaces', 'managed database'],
  },
  'discord': {
    name: 'Discord',
    type: 'statuspage',
    websiteUrl: 'https://discord.com',
    statusPageUrl: 'https://discordstatus.com',
    relatedDomains: ['discord.com', '*.discord.com', 'discordapp.com'],
    searchAliases: ['chat', 'gaming', 'community', 'voice', 'server', 'bot'],
  },
  'docker': {
    name: 'Docker',
    type: 'statusio',
    websiteUrl: 'https://docker.com',
    statusPageUrl: 'https://www.dockerstatus.com',
    pageId:  '533c6539221ae15e3f000031',
    relatedDomains: ['docker.com', '*.docker.com', 'dockerhub.com'],
    searchAliases: ['containers', 'hub', 'registry', 'dockerfile', 'compose'],
  },
  'doppler': {
    name: 'Doppler',
    type: 'statuspage',
    websiteUrl: 'https://doppler.com',
    statusPageUrl: 'https://www.dopplerstatus.com',
    relatedDomains: ['doppler.com', '*.doppler.com'],
    searchAliases: ['secrets', 'environment variables', 'env vars', 'secret management', 'configuration'],
  },
  'docusign': {
    name: 'DocuSign',
    type: 'statuspage',
    websiteUrl: 'https://docusign.com',
    statusPageUrl: 'https://status.docusign.com',
    relatedDomains: ['docusign.com', '*.docusign.com', 'docusign.net', '*.docusign.net'],
    searchAliases: ['e-signature', 'esign', 'document signing', 'contracts'],
  },
  'dropbox': {
    name: 'Dropbox',
    type: 'statuspage',
    websiteUrl: 'https://dropbox.com',
    statusPageUrl: 'https://status.dropbox.com',
    relatedDomains: ['dropbox.com', '*.dropbox.com', 'dropboxbusiness.com'],
    searchAliases: ['file storage', 'cloud storage', 'sync', 'file sharing'],
  },
  'e2b': {
    name: 'E2B',
    type: 'statuspage',
    websiteUrl: 'https://e2b.dev',
    statusPageUrl: 'https://status.e2b.dev',
    relatedDomains: ['e2b.dev', '*.e2b.dev'],
    searchAliases: ['sandbox', 'code interpreter', 'ai agents'],
  },
  'elastic': {
    name: 'Elastic Cloud',
    type: 'statuspage',
    websiteUrl: 'https://elastic.co',
    statusPageUrl: 'https://status.elastic.co',
    relatedDomains: ['elastic.co', '*.elastic.co', 'elasticsearch.com', 'found.no'],
    searchAliases: ['elasticsearch', 'kibana', 'logstash', 'beats', 'observability', 'search', 'ecs'],
  },
  'elevenlabs': {
    name: 'ElevenLabs',
    type: 'statuspage',
    websiteUrl: 'https://elevenlabs.io',
    statusPageUrl: 'https://status.elevenlabs.io',
    relatedDomains: ['elevenlabs.io', '*.elevenlabs.io'],
    searchAliases: ['tts', 'voice', 'speech', 'ai'],
  },
  'expo': {
    name: 'Expo',
    type: 'statuspage',
    websiteUrl: 'https://expo.dev',
    statusPageUrl: 'https://status.expo.dev',
    relatedDomains: ['expo.dev', '*.expo.dev', 'expo.io', '*.expo.io'],
    searchAliases: ['react native', 'mobile', 'ios', 'android', 'eas', 'build', 'ota updates'],
  },
  'fastly': {
    name: 'Fastly',
    type: 'statuscast',
    websiteUrl: 'https://fastly.com',
    statusPageUrl: 'https://www.fastlystatus.com',
    relatedDomains: ['fastly.com', '*.fastly.com', 'fastly.net', '*.fastly.net'],
    searchAliases: ['cdn', 'edge', 'cache', 'waf', 'streaming'],
  },
  'figma': {
    name: 'Figma',
    type: 'statuspage',
    websiteUrl: 'https://figma.com',
    statusPageUrl: 'https://status.figma.com',
    relatedDomains: ['figma.com', '*.figma.com'],
    searchAliases: ['design', 'prototyping', 'ui', 'ux', 'wireframe'],
  },
  'filestack': {
    name: 'Filestack',
    type: 'statuspage',
    websiteUrl: 'https://filestack.com',
    statusPageUrl: 'https://status.filestack.com',
    relatedDomains: ['filestack.com', '*.filestack.com'],
    searchAliases: ['file upload', 'cdn', 'images'],
  },
  'fireworks': {
    name: 'Fireworks AI',
    type: 'statuspage',
    websiteUrl: 'https://fireworks.ai',
    statusPageUrl: 'https://status.fireworks.ai',
    relatedDomains: ['fireworks.ai', '*.fireworks.ai'],
    searchAliases: ['inference', 'llm', 'ai'],
  },
  'fivetran': {
    name: 'Fivetran',
    type: 'statuspage',
    websiteUrl: 'https://fivetran.com',
    statusPageUrl: 'https://status.fivetran.com',
    relatedDomains: ['fivetran.com', '*.fivetran.com'],
    searchAliases: ['etl', 'data pipeline', 'data integration', 'connector', 'elt', 'warehouse'],
  },
  'flyio': {
    name: 'Fly.io',
    type: 'statuspage',
    websiteUrl: 'https://fly.io',
    statusPageUrl: 'https://status.flyio.net',
    relatedDomains: ['fly.io', '*.fly.io'],
    searchAliases: ['hosting', 'deployment', 'containers', 'paas'],
  },
  'front': {
    name: 'Front',
    type: 'statuspage',
    websiteUrl: 'https://front.com',
    statusPageUrl: 'https://front.statuspage.io',
    relatedDomains: ['front.com', '*.front.com', 'frontapp.com', '*.frontapp.com'],
    searchAliases: ['shared inbox', 'support', 'email'],
  },
  'frontegg': {
    name: 'Frontegg',
    type: 'statuspage',
    websiteUrl: 'https://frontegg.com',
    statusPageUrl: 'https://status.frontegg.com',
    relatedDomains: ['frontegg.com', '*.frontegg.com'],
    searchAliases: ['auth', 'identity', 'user management'],
  },
  'fusionauth': {
    name: 'FusionAuth',
    type: 'statuspage',
    websiteUrl: 'https://fusionauth.io',
    statusPageUrl: 'https://status.fusionauth.io',
    relatedDomains: ['fusionauth.io', '*.fusionauth.io'],
    searchAliases: ['auth', 'identity', 'sso', 'oauth'],
  },
  'github': {
    name: 'GitHub',
    type: 'statuspage',
    websiteUrl: 'https://github.com',
    statusPageUrl: 'https://www.githubstatus.com',
    relatedDomains: ['github.com', '*.github.com'],
    searchAliases: ['git', 'repos', 'actions', 'copilot', 'packages', 'pages', 'gist', 'pull request'],
  },
  'gitlab': {
    name: 'GitLab',
    type: 'statusio',
    websiteUrl: 'https://gitlab.com',
    statusPageUrl: 'https://status.gitlab.com',
    pageId:  '5b36dc6502d06804c08349f7',
    relatedDomains: ['gitlab.com', '*.gitlab.com'],
    searchAliases: ['git', 'ci/cd', 'devops', 'repos', 'pipeline', 'merge request'],
  },
  'google-cloud': {
    name: 'Google Cloud',
    type: 'google',
    websiteUrl: 'https://cloud.google.com',
    statusPageUrl: 'https://status.cloud.google.com',
    relatedDomains: [
      'cloud.google.com', 'googleapis.com', '*.googleapis.com',
      'googlecloud.com', '*.googlecloud.com',
    ],
    searchAliases: ['gcp', 'gce', 'gke', 'bigquery', 'firebase', 'compute engine', 'cloud run', 'cloud functions', 'pubsub', 'spanner', 'gemini', 'vertex ai', 'vertex', 'ai studio', 'gemini api', 'gemini code assist'],
  },
  'google-workspace': {
    name: 'Google Workspace',
    type: 'google',
    websiteUrl: 'https://workspace.google.com',
    statusPageUrl: 'https://www.google.com/appsstatus/dashboard',
    relatedDomains: [
      'workspace.google.com',
      'gmail.com', 'drive.google.com', 'docs.google.com',
      'sheets.google.com', 'slides.google.com', 'meet.google.com',
      'calendar.google.com', 'chat.google.com', 'mail.google.com',
    ],
    searchAliases: ['gmail', 'google drive', 'google docs', 'google sheets', 'google meet', 'google calendar', 'google chat', 'g suite', 'gsuite', 'google mail'],
  },
  'grafana': {
    name: 'Grafana',
    type: 'statuspage',
    websiteUrl: 'https://grafana.com',
    statusPageUrl: 'https://status.grafana.com',
    relatedDomains: ['grafana.com', '*.grafana.com', 'grafana.net', '*.grafana.net'],
    searchAliases: ['monitoring', 'dashboards', 'prometheus', 'loki', 'mimir', 'tempo', 'observability'],
  },
  'graphite': {
    name: 'Graphite',
    type: 'instatus',
    websiteUrl: 'https://graphite.dev',
    statusPageUrl: 'https://status.graphite.dev',
    relatedDomains: ['graphite.dev', '*.graphite.dev'],
    searchAliases: ['stacked prs', 'code review', 'git'],
  },
  'groq': {
    name: 'Groq',
    type: 'incidentio',
    websiteUrl: 'https://groq.com',
    statusPageUrl: 'https://groqstatus.com',
    relatedDomains: ['groq.com', '*.groq.com'],
    searchAliases: ['ai', 'llm', 'inference', 'llama', 'mixtral', 'whisper', 'language model'],
  },
  'harvest': {
    name: 'Harvest',
    type: 'statuspage',
    websiteUrl: 'https://harvestapp.com',
    statusPageUrl: 'https://www.harveststatus.com',
    relatedDomains: ['harvestapp.com', '*.harvestapp.com', 'getharvest.com', '*.getharvest.com'],
    searchAliases: ['time tracking', 'invoicing', 'timesheets', 'billing'],
  },
  'hashicorp': {
    name: 'HashiCorp',
    type: 'incidentio',
    websiteUrl: 'https://hashicorp.com',
    statusPageUrl: 'https://status.hashicorp.com',
    relatedDomains: ['hashicorp.com', '*.hashicorp.com', 'terraform.io', '*.terraform.io', 'vagrantup.com'],
    searchAliases: ['terraform', 'vault', 'consul', 'nomad', 'packer', 'waypoint', 'hcp', 'infrastructure as code', 'iac', 'secrets'],
  },
  'hasura': {
    name: 'Hasura',
    type: 'incidentio',
    websiteUrl: 'https://hasura.io',
    statusPageUrl: 'https://hasura-status.com',
    relatedDomains: ['hasura.io', '*.hasura.io'],
    searchAliases: ['graphql', 'database', 'api', 'postgres'],
  },
  'heap': {
    name: 'Heap',
    type: 'statuspage',
    websiteUrl: 'https://heap.io',
    statusPageUrl: 'https://status.heap.io',
    relatedDomains: ['heap.io', '*.heap.io'],
    searchAliases: ['analytics', 'product analytics', 'events'],
  },
  'helpscout': {
    name: 'Help Scout',
    type: 'statuspage',
    websiteUrl: 'https://helpscout.com',
    statusPageUrl: 'https://status.helpscout.com',
    relatedDomains: ['helpscout.com', '*.helpscout.com', 'helpscout.net', '*.helpscout.net'],
    searchAliases: ['helpdesk', 'support', 'shared inbox'],
  },
  'heroku': {
    name: 'Heroku',
    type: 'heroku',
    websiteUrl: 'https://heroku.com',
    statusPageUrl: 'https://status.heroku.com',
    relatedDomains: ['heroku.com', '*.heroku.com', 'herokuapp.com'],
    searchAliases: ['paas', 'hosting', 'deployment', 'dyno', 'salesforce'],
  },
  'honeybadger': {
    name: 'Honeybadger',
    type: 'statuspage',
    websiteUrl: 'https://honeybadger.io',
    statusPageUrl: 'https://status.honeybadger.io',
    relatedDomains: ['honeybadger.io', '*.honeybadger.io'],
    searchAliases: ['error tracking', 'monitoring', 'uptime'],
  },
  'honeycomb': {
    name: 'Honeycomb',
    type: 'statuspage',
    websiteUrl: 'https://honeycomb.io',
    statusPageUrl: 'https://status.honeycomb.io',
    relatedDomains: ['honeycomb.io', '*.honeycomb.io'],
    searchAliases: ['observability', 'distributed tracing', 'apm', 'debugging', 'monitoring', 'events'],
  },
  'hubspot': {
    name: 'HubSpot',
    type: 'statuspage',
    websiteUrl: 'https://hubspot.com',
    statusPageUrl: 'https://status.hubspot.com',
    relatedDomains: ['hubspot.com', '*.hubspot.com', 'hubspotusercontent.com'],
    searchAliases: ['crm', 'marketing', 'sales', 'email marketing', 'automation'],
  },
  'imgix': {
    name: 'imgix',
    type: 'statuspage',
    websiteUrl: 'https://imgix.com',
    statusPageUrl: 'https://status.imgix.com',
    relatedDomains: ['imgix.com', '*.imgix.com'],
    searchAliases: ['images', 'cdn', 'transformation'],
  },
  'infisical': {
    name: 'Infisical',
    type: 'statuspage',
    websiteUrl: 'https://infisical.com',
    statusPageUrl: 'https://status.infisical.com',
    relatedDomains: ['infisical.com', '*.infisical.com'],
    searchAliases: ['secrets', 'env', 'security'],
  },
  'influxdata': {
    name: 'InfluxDB',
    type: 'statuspage',
    websiteUrl: 'https://influxdata.com',
    statusPageUrl: 'https://status.influxdata.com',
    relatedDomains: ['influxdata.com', '*.influxdata.com'],
    searchAliases: ['timeseries', 'metrics', 'database'],
  },
  'infura': {
    name: 'Infura',
    type: 'statuspage',
    websiteUrl: 'https://infura.io',
    statusPageUrl: 'https://status.infura.io',
    relatedDomains: ['infura.io', '*.infura.io'],
    searchAliases: ['web3', 'ethereum', 'ipfs', 'blockchain', 'rpc', 'node', 'metamask'],
  },
  // Intercom retired intercomstatus.com: it now redirects to the Fin status
  // page. That page exposes no /api/v2/incidents/unresolved.json and no
  // `shortlink` on incidents, so it must be read as `incidentio`
  // (/api/v2/incidents.json, resolved filtered client-side), not `statuspage`.
  'inngest': {
    name: 'Inngest',
    type: 'statuspage',
    websiteUrl: 'https://inngest.com',
    statusPageUrl: 'https://status.inngest.com',
    relatedDomains: ['inngest.com', '*.inngest.com'],
    searchAliases: ['queues', 'workflows', 'background jobs'],
  },
  'intercom': {
    name: 'Intercom',
    type: 'incidentio',
    websiteUrl: 'https://intercom.com',
    statusPageUrl: 'https://www.finstatus.com',
    relatedDomains: ['intercom.com', '*.intercom.com', 'intercom.io', '*.intercom.io'],
    searchAliases: ['customer support', 'chat', 'messaging', 'helpdesk', 'live chat'],
  },
  'iterable': {
    name: 'Iterable',
    type: 'statuspage',
    websiteUrl: 'https://iterable.com',
    statusPageUrl: 'https://status.iterable.com',
    relatedDomains: ['iterable.com', '*.iterable.com'],
    searchAliases: ['marketing automation', 'messaging'],
  },
  'jfrog': {
    name: 'JFrog',
    type: 'statuspage',
    websiteUrl: 'https://jfrog.com',
    statusPageUrl: 'https://status.jfrog.io',
    relatedDomains: ['jfrog.com', '*.jfrog.com'],
    searchAliases: ['artifactory', 'registry', 'artifacts'],
  },
  'jina': {
    name: 'Jina AI',
    type: 'statuspage',
    websiteUrl: 'https://jina.ai',
    statusPageUrl: 'https://status.jina.ai',
    relatedDomains: ['jina.ai', '*.jina.ai'],
    searchAliases: ['embeddings', 'search', 'ai'],
  },
  'jira': {
    name: 'Jira',
    type: 'statuspage',
    websiteUrl: 'https://atlassian.com/software/jira',
    statusPageUrl: 'https://jira-software.status.atlassian.com',
    relatedDomains: ['atlassian.net', '*.atlassian.net', 'jira.com', '*.jira.com'],
    searchAliases: ['issue tracker', 'agile', 'tickets', 'atlassian'],
  },
  'jwplayer': {
    name: 'JW Player',
    type: 'statuspage',
    websiteUrl: 'https://jwplayer.com',
    statusPageUrl: 'https://status.jwplayer.com',
    relatedDomains: ['jwplayer.com', '*.jwplayer.com', 'jwplatform.com', '*.jwplatform.com'],
    searchAliases: ['video', 'player', 'streaming'],
  },
  'kinde': {
    name: 'Kinde',
    type: 'instatus',
    websiteUrl: 'https://kinde.com',
    statusPageUrl: 'https://status.kinde.com',
    relatedDomains: ['kinde.com', '*.kinde.com'],
    searchAliases: ['auth', 'identity', 'user management'],
  },
  'klaviyo': {
    name: 'Klaviyo',
    type: 'statuspage',
    websiteUrl: 'https://klaviyo.com',
    statusPageUrl: 'https://status.klaviyo.com',
    relatedDomains: ['klaviyo.com', '*.klaviyo.com'],
    searchAliases: ['email marketing', 'ecommerce', 'sms'],
  },
  'knock': {
    name: 'Knock',
    type: 'statuspage',
    websiteUrl: 'https://knock.app',
    statusPageUrl: 'https://status.knock.app',
    relatedDomains: ['knock.app', '*.knock.app'],
    searchAliases: ['notifications', 'messaging', 'in-app'],
  },
  'kong': {
    name: 'Kong',
    type: 'statuspage',
    websiteUrl: 'https://konghq.com',
    statusPageUrl: 'https://kong.statuspage.io',
    relatedDomains: ['konghq.com', '*.konghq.com'],
    searchAliases: ['api gateway', 'api management', 'service mesh', 'proxy', 'plugins'],
  },
  'koyeb': {
    name: 'Koyeb',
    type: 'instatus',
    websiteUrl: 'https://koyeb.com',
    statusPageUrl: 'https://status.koyeb.com',
    relatedDomains: ['koyeb.com', '*.koyeb.com'],
    searchAliases: ['paas', 'deploy', 'serverless'],
  },
  'lambdalabs': {
    name: 'Lambda',
    type: 'statuspage',
    websiteUrl: 'https://lambdalabs.com',
    statusPageUrl: 'https://status.lambda.ai',
    relatedDomains: ['lambdalabs.com', '*.lambdalabs.com', 'lambda.ai', '*.lambda.ai'],
    searchAliases: ['gpu', 'cloud', 'ai', 'compute'],
  },
  'launchdarkly': {
    name: 'LaunchDarkly',
    type: 'statuspage',
    websiteUrl: 'https://launchdarkly.com',
    statusPageUrl: 'https://status.launchdarkly.com',
    relatedDomains: ['launchdarkly.com', '*.launchdarkly.com'],
    searchAliases: ['feature flags', 'feature toggles', 'feature management', 'a/b testing'],
  },
  'letsencrypt': {
    name: "Let's Encrypt",
    type: 'statusio',
    websiteUrl: 'https://letsencrypt.org',
    statusPageUrl: 'https://letsencrypt.status.io',
    pageId: '55957a99e800baa4470002da',
    relatedDomains: ['letsencrypt.org', '*.letsencrypt.org'],
    searchAliases: ['ssl', 'tls', 'certificate', 'acme', 'https', 'certificate authority', 'free ssl'],
  },
  'linear': {
    name: 'Linear',
    type: 'incidentio',
    websiteUrl: 'https://linear.app',
    statusPageUrl: 'https://linearstatus.com',
    relatedDomains: ['linear.app', '*.linear.app'],
    searchAliases: ['project management', 'issues', 'tickets', 'sprint', 'roadmap'],
  },
  'linode': {
    name: 'Akamai Linode',
    type: 'statuspage',
    websiteUrl: 'https://linode.com',
    statusPageUrl: 'https://status.linode.com',
    relatedDomains: ['linode.com', '*.linode.com', 'akamai.com', '*.akamai.com'],
    searchAliases: ['cloud', 'vps', 'hosting'],
  },
  'liveblocks': {
    name: 'Liveblocks',
    type: 'statuspage',
    websiteUrl: 'https://liveblocks.io',
    statusPageUrl: 'https://liveblocks.statuspage.io',
    relatedDomains: ['liveblocks.io', '*.liveblocks.io'],
    searchAliases: ['realtime', 'collaboration', 'multiplayer', 'presence', 'yjs', 'conflict-free'],
  },
  'livekit': {
    name: 'LiveKit',
    type: 'statuspage',
    websiteUrl: 'https://livekit.io',
    statusPageUrl: 'https://status.livekit.io',
    relatedDomains: ['livekit.io', '*.livekit.io'],
    searchAliases: ['webrtc', 'realtime', 'video', 'agents'],
  },
  'logrocket': {
    name: 'LogRocket',
    type: 'incidentio',
    websiteUrl: 'https://logrocket.com',
    statusPageUrl: 'https://status.logrocket.com',
    relatedDomains: ['logrocket.com', '*.logrocket.com'],
    searchAliases: ['session replay', 'frontend monitoring'],
  },
  'loom': {
    name: 'Loom',
    type: 'statuspage',
    websiteUrl: 'https://loom.com',
    statusPageUrl: 'https://loom.status.atlassian.com',
    relatedDomains: ['loom.com', '*.loom.com'],
    searchAliases: ['video', 'screen recording', 'async video', 'screen capture'],
  },
  'lucid': {
    name: 'Lucid',
    type: 'statuspage',
    websiteUrl: 'https://lucid.co',
    statusPageUrl: 'https://status.lucid.co',
    relatedDomains: ['lucid.co', '*.lucid.co'],
    searchAliases: ['diagrams', 'whiteboard', 'lucidchart'],
  },
  'mailgun': {
    name: 'Mailgun',
    type: 'statuspage',
    websiteUrl: 'https://mailgun.com',
    statusPageUrl: 'https://status.mailgun.com',
    relatedDomains: ['mailgun.com', '*.mailgun.com', 'mailgun.net', '*.mailgun.net'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email api', 'sending'],
  },
  'manageengine': {
    name: 'ManageEngine',
    type: 'site24x7',
    websiteUrl: 'https://manageengine.com',
    statusPageUrl: 'https://status.manageengine.com',
    relatedDomains: ['manageengine.com', '*.manageengine.com'],
    searchAliases: ['it management', 'helpdesk', 'service desk', 'endpoint management', 'patch management', 'ad manager'],
  },
  'mastodon': {
    name: 'Mastodon Social',
    type: 'instatus',
    websiteUrl: 'https://mastodon.social',
    statusPageUrl: 'https://status.mastodon.social',
    relatedDomains: ['mastodon.social', '*.mastodon.social'],
    searchAliases: ['fediverse', 'activitypub', 'microblogging', 'social media'],
  },
  'materialize': {
    name: 'Materialize',
    type: 'statuspage',
    websiteUrl: 'https://materialize.com',
    statusPageUrl: 'https://status.materialize.com',
    relatedDomains: ['materialize.com', '*.materialize.com'],
    searchAliases: ['streaming', 'sql', 'database'],
  },
  'mergify': {
    name: 'Mergify',
    type: 'statuspage',
    websiteUrl: 'https://mergify.com',
    statusPageUrl: 'https://status.mergify.com',
    relatedDomains: ['mergify.com', '*.mergify.com'],
    searchAliases: ['merge queue', 'ci', 'automation'],
  },
  'metabase': {
    name: 'Metabase',
    type: 'statuspage',
    websiteUrl: 'https://metabase.com',
    statusPageUrl: 'https://status.metabase.com',
    relatedDomains: ['metabase.com', '*.metabase.com'],
    searchAliases: ['business intelligence', 'bi', 'analytics', 'dashboards', 'data visualization'],
  },
  'mistral': {
    name: 'Mistral AI',
    type: 'checkly',
    websiteUrl: 'https://mistral.ai',
    statusPageUrl: 'https://status.mistral.ai',
    slug: 'mistral-ai',
    relatedDomains: ['mistral.ai', '*.mistral.ai'],
    searchAliases: ['ai', 'llm', 'language model', 'inference', 'mistral'],
  },
  'miro': {
    name: 'Miro',
    type: 'incidentio',
    websiteUrl: 'https://miro.com',
    statusPageUrl: 'https://status.miro.com',
    relatedDomains: ['miro.com', '*.miro.com'],
    searchAliases: ['whiteboard', 'collaboration', 'design', 'mind map', 'brainstorming'],
  },
  'mixpanel': {
    name: 'Mixpanel',
    type: 'statuspage',
    websiteUrl: 'https://mixpanel.com',
    statusPageUrl: 'https://www.mixpanelstatus.com',
    relatedDomains: ['mixpanel.com', '*.mixpanel.com'],
    searchAliases: ['analytics', 'product analytics', 'events', 'funnel', 'retention'],
  },
  'mollie': {
    name: 'Mollie',
    type: 'instatus',
    websiteUrl: 'https://mollie.com',
    statusPageUrl: 'https://status.mollie.com',
    relatedDomains: ['mollie.com', '*.mollie.com'],
    searchAliases: ['payments', 'psp', 'ideal'],
  },
  'monday': {
    name: 'monday.com',
    type: 'statuspage',
    websiteUrl: 'https://monday.com',
    statusPageUrl: 'https://status.monday.com',
    relatedDomains: ['monday.com', '*.monday.com'],
    searchAliases: ['project management', 'work os', 'crm'],
  },
  'mongodb': {
    name: 'MongoDB Atlas',
    type: 'statuspage',
    websiteUrl: 'https://mongodb.com',
    statusPageUrl: 'https://status.mongodb.com',
    relatedDomains: ['mongodb.com', '*.mongodb.com', 'mongodb.net', '*.mongodb.net'],
    searchAliases: ['mongodb', 'database', 'nosql', 'atlas', 'document store'],
  },
  'mural': {
    name: 'Mural',
    type: 'statuspage',
    websiteUrl: 'https://mural.co',
    statusPageUrl: 'https://status.mural.co',
    relatedDomains: ['mural.co', '*.mural.co'],
    searchAliases: ['whiteboard', 'collaboration', 'diagrams'],
  },
  'mux': {
    name: 'Mux',
    type: 'statuspage',
    websiteUrl: 'https://mux.com',
    statusPageUrl: 'https://status.mux.com',
    relatedDomains: ['mux.com', '*.mux.com'],
    searchAliases: ['video', 'video api', 'live streaming', 'video hosting', 'hls', 'player'],
  },
  'n8n': {
    name: 'n8n',
    type: 'statuspage',
    websiteUrl: 'https://n8n.io',
    statusPageUrl: 'https://n8n.statuspage.io',
    relatedDomains: ['n8n.io', '*.n8n.io'],
    searchAliases: ['workflow', 'automation', 'self-hosted', 'integration', 'zapier alternative', 'no-code'],
  },
  'nabucasa': {
    name: 'Nabu Casa',
    type: 'statuspage',
    websiteUrl: 'https://nabucasa.com',
    statusPageUrl: 'https://status.nabucasa.com',
    relatedDomains: ['nabucasa.com', '*.nabucasa.com'],
    searchAliases: ['home assistant', 'home assistant cloud', 'smart home', 'iot', 'hass'],
  },
  'neo4j': {
    name: 'Neo4j Aura',
    type: 'statuspage',
    websiteUrl: 'https://neo4j.com',
    statusPageUrl: 'https://status.neo4j.io',
    relatedDomains: ['neo4j.com', '*.neo4j.com'],
    searchAliases: ['graph database', 'cypher'],
  },
  'neon': {
    name: 'Neon',
    type: 'statusio',
    websiteUrl: 'https://neon.tech',
    statusPageUrl: 'https://neonstatus.com',
    pageId:  '6878fc85709daa75be6c7e3c',
    relatedDomains: ['neon.tech', '*.neon.tech'],
    searchAliases: ['postgres', 'postgresql', 'serverless', 'database', 'branching'],
  },
  'netlify': {
    name: 'Netlify',
    type: 'statuspage',
    websiteUrl: 'https://netlify.com',
    statusPageUrl: 'https://netlifystatus.com',
    relatedDomains: ['netlify.com', '*.netlify.com'],
    searchAliases: ['hosting', 'jamstack', 'deployment', 'static site', 'frontend', 'edge functions'],
  },
  'newrelic': {
    name: 'New Relic',
    type: 'statuspage',
    websiteUrl: 'https://newrelic.com',
    statusPageUrl: 'https://status.newrelic.com',
    relatedDomains: ['newrelic.com', '*.newrelic.com'],
    searchAliases: ['monitoring', 'apm', 'observability', 'logs', 'metrics', 'tracing'],
  },
  'ngrok': {
    name: 'ngrok',
    type: 'statuspage',
    websiteUrl: 'https://ngrok.com',
    statusPageUrl: 'https://status.ngrok.com',
    relatedDomains: ['ngrok.com', '*.ngrok.com', 'ngrok.io', '*.ngrok.io'],
    searchAliases: ['tunnel', 'tunneling', 'localhost', 'webhook', 'reverse proxy', 'expose'],
  },
  'nhost': {
    name: 'Nhost',
    type: 'instatus',
    websiteUrl: 'https://nhost.io',
    statusPageUrl: 'https://status.nhost.io',
    relatedDomains: ['nhost.io', '*.nhost.io', 'nhost.run', '*.nhost.run'],
    searchAliases: ['backend', 'baas', 'graphql', 'postgres'],
  },
  'northflank': {
    name: 'Northflank',
    type: 'instatus',
    websiteUrl: 'https://northflank.com',
    statusPageUrl: 'https://status.northflank.com',
    relatedDomains: ['northflank.com', '*.northflank.com'],
    searchAliases: ['paas', 'deploy', 'kubernetes'],
  },
  'notion': {
    name: 'Notion',
    type: 'statuspage',
    websiteUrl: 'https://notion.so',
    statusPageUrl: 'https://www.notion-status.com',
    relatedDomains: ['notion.so', '*.notion.so', 'notion.com', '*.notion.com'],
    searchAliases: ['notes', 'wiki', 'docs', 'workspace', 'knowledge base', 'database'],
  },
  'novu': {
    name: 'Novu',
    type: 'instatus',
    websiteUrl: 'https://novu.co',
    statusPageUrl: 'https://novu.instatus.com',
    relatedDomains: ['novu.co', '*.novu.co'],
    searchAliases: ['notifications', 'messaging', 'in-app'],
  },
  'npm': {
    name: 'npm',
    type: 'statuspage',
    websiteUrl: 'https://npmjs.com',
    statusPageUrl: 'https://status.npmjs.org',
    relatedDomains: ['npmjs.com', 'npmjs.org', 'npm.com'],
    searchAliases: ['node', 'nodejs', 'package manager', 'registry', 'javascript', 'packages'],
  },
  'ona': {
    name: 'Ona',
    type: 'statuspage',
    websiteUrl: 'https://gitpod.io',
    statusPageUrl: 'https://onastatus.com',
    relatedDomains: ['ona.com', '*.ona.com', 'gitpod.io', '*.gitpod.io'],
    searchAliases: ['gitpod', 'cloud ide', 'dev environment', 'workspace'],
  },
  'onesignal': {
    name: 'OneSignal',
    type: 'statuspage',
    websiteUrl: 'https://onesignal.com',
    statusPageUrl: 'https://status.onesignal.com',
    relatedDomains: ['onesignal.com', '*.onesignal.com'],
    searchAliases: ['push notifications', 'messaging'],
  },
  'openai': {
    name: 'OpenAI',
    type: 'incidentio',
    websiteUrl: 'https://openai.com',
    statusPageUrl: 'https://status.openai.com',
    relatedDomains: ['openai.com', '*.openai.com', 'chatgpt.com', '*.chatgpt.com'],
    searchAliases: ['chatgpt', 'gpt', 'gpt-4', 'ai', 'llm', 'dall-e', 'whisper'],
  },
  'opsgenie': {
    name: 'Opsgenie',
    type: 'incidentio',
    websiteUrl: 'https://atlassian.com/software/opsgenie',
    statusPageUrl: 'https://opsgenie.status.atlassian.com',
    relatedDomains: ['opsgenie.com', '*.opsgenie.com'],
    searchAliases: ['on-call', 'alerting', 'incident', 'atlassian'],
  },
  'packagist': {
    name: 'Packagist',
    type: 'uptimerobot',
    websiteUrl: 'https://packagist.org',
    statusPageUrl: 'https://status.packagist.org',
    relatedDomains: ['packagist.org', '*.packagist.org'],
    searchAliases: ['php', 'composer', 'package manager', 'registry'],
  },
  'pagerduty': {
    name: 'PagerDuty',
    type: 'pagerduty',
    websiteUrl: 'https://pagerduty.com',
    statusPageUrl: 'https://status.pagerduty.com',
    relatedDomains: ['pagerduty.com', '*.pagerduty.com'],
    searchAliases: ['on-call', 'alerting', 'incident management', 'ops', 'devops'],
  },
  'pandadoc': {
    name: 'PandaDoc',
    type: 'statuspage',
    websiteUrl: 'https://pandadoc.com',
    statusPageUrl: 'https://status.pandadoc.com',
    relatedDomains: ['pandadoc.com', '*.pandadoc.com'],
    searchAliases: ['e-signature', 'esign', 'proposals', 'contracts', 'documents'],
  },
  'pendo': {
    name: 'Pendo',
    type: 'statuspage',
    websiteUrl: 'https://pendo.io',
    statusPageUrl: 'https://status.pendo.io',
    relatedDomains: ['pendo.io', '*.pendo.io'],
    searchAliases: ['product analytics', 'onboarding', 'in-app'],
  },
  'perplexity': {
    name: 'Perplexity',
    type: 'instatus',
    websiteUrl: 'https://perplexity.ai',
    statusPageUrl: 'https://status.perplexity.com',
    relatedDomains: ['perplexity.ai', '*.perplexity.ai'],
    searchAliases: ['ai search', 'llm', 'answers'],
  },
  'pinecone': {
    name: 'Pinecone',
    type: 'statuspage',
    websiteUrl: 'https://pinecone.io',
    statusPageUrl: 'https://status.pinecone.io',
    relatedDomains: ['pinecone.io', '*.pinecone.io'],
    searchAliases: ['vector database', 'embeddings', 'ai', 'semantic search', 'rag', 'similarity search'],
  },
  'plaid': {
    name: 'Plaid',
    type: 'statuspage',
    websiteUrl: 'https://plaid.com',
    statusPageUrl: 'https://status.plaid.com',
    relatedDomains: ['plaid.com', '*.plaid.com'],
    searchAliases: ['fintech', 'banking', 'open banking', 'financial data', 'bank connection'],
  },
  'planetscale': {
    name: 'PlanetScale',
    type: 'statuspage',
    websiteUrl: 'https://planetscale.com',
    statusPageUrl: 'https://www.planetscalestatus.com',
    relatedDomains: ['planetscale.com', '*.planetscale.com'],
    searchAliases: ['mysql', 'database', 'serverless db', 'vitess'],
  },
  'plivo': {
    name: 'Plivo',
    type: 'statuspage',
    websiteUrl: 'https://plivo.com',
    statusPageUrl: 'https://status.plivo.com',
    relatedDomains: ['plivo.com', '*.plivo.com'],
    searchAliases: ['sms', 'voice', 'communications'],
  },
  'posthog': {
    name: 'PostHog',
    type: 'posthog',
    websiteUrl: 'https://posthog.com',
    statusPageUrl: 'https://www.posthogstatus.com',
    relatedDomains: ['posthog.com', '*.posthog.com'],
    searchAliases: ['analytics', 'product analytics', 'feature flags', 'session recording', 'funnels'],
  },
  'postman': {
    name: 'Postman',
    type: 'statuspage',
    websiteUrl: 'https://postman.com',
    statusPageUrl: 'https://status.postman.com',
    relatedDomains: ['postman.com', '*.postman.com'],
    searchAliases: ['api client', 'testing', 'collections'],
  },
  'postmark': {
    name: 'Postmark',
    type: 'sorryapp',
    websiteUrl: 'https://postmarkapp.com',
    statusPageUrl: 'https://status.postmarkapp.com',
    relatedDomains: ['postmarkapp.com', '*.postmarkapp.com'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email delivery'],
  },
  'prisma': {
    name: 'Prisma',
    type: 'statuspage',
    websiteUrl: 'https://prisma.io',
    statusPageUrl: 'https://prisma.statuspage.io',
    relatedDomains: ['prisma.io', '*.prisma.io'],
    searchAliases: ['orm', 'database', 'typescript', 'postgres', 'mysql', 'mongodb', 'query builder'],
  },
  'prismic': {
    name: 'Prismic',
    type: 'statuspage',
    websiteUrl: 'https://prismic.io',
    statusPageUrl: 'https://status.prismic.io',
    relatedDomains: ['prismic.io', '*.prismic.io'],
    searchAliases: ['cms', 'headless', 'content'],
  },
  'proton': {
    name: 'Proton',
    type: 'statuspage',
    websiteUrl: 'https://proton.me',
    statusPageUrl: 'https://status.proton.me',
    relatedDomains: ['proton.me', '*.proton.me', 'protonmail.com', '*.protonmail.com', 'protonvpn.com'],
    searchAliases: ['protonmail', 'proton vpn', 'proton drive', 'email', 'privacy', 'encrypted'],
  },
  'pubnub': {
    name: 'PubNub',
    type: 'statuspage',
    websiteUrl: 'https://pubnub.com',
    statusPageUrl: 'https://status.pubnub.com',
    relatedDomains: ['pubnub.com', '*.pubnub.com'],
    searchAliases: ['realtime', 'websocket', 'pubsub', 'messaging'],
  },
  'pulumi': {
    name: 'Pulumi',
    type: 'statuspage',
    websiteUrl: 'https://pulumi.com',
    statusPageUrl: 'https://status.pulumi.com',
    relatedDomains: ['pulumi.com', '*.pulumi.com'],
    searchAliases: ['iac', 'infrastructure as code', 'terraform'],
  },
  'pusher': {
    name: 'Pusher',
    type: 'statuspage',
    websiteUrl: 'https://pusher.com',
    statusPageUrl: 'https://status.pusher.com',
    relatedDomains: ['pusher.com', '*.pusher.com'],
    searchAliases: ['realtime', 'websocket', 'pubsub'],
  },
  'python': {
    name: 'Python Infrastructure',
    type: 'statuspage',
    websiteUrl: 'https://python.org',
    statusPageUrl: 'https://status.python.org',
    relatedDomains: ['python.org', '*.python.org', 'pypi.org', '*.pypi.org'],
    searchAliases: ['pypi', 'pip', 'python'],
  },
  'quicknode': {
    name: 'QuickNode',
    type: 'statuspage',
    websiteUrl: 'https://quicknode.com',
    statusPageUrl: 'https://status.quicknode.com',
    relatedDomains: ['quicknode.com', '*.quicknode.com'],
    searchAliases: ['web3', 'blockchain', 'ethereum', 'solana', 'rpc', 'node', 'infrastructure'],
  },
  'railway': {
    name: 'Railway',
    type: 'instatus',
    websiteUrl: 'https://railway.com',
    statusPageUrl: 'https://railway.instatus.com',
    relatedDomains: ['railway.com', '*.railway.com', 'railway.app', '*.railway.app'],
    searchAliases: ['paas', 'deploy', 'hosting'],
  },
  'recurly': {
    name: 'Recurly',
    type: 'statuspage',
    websiteUrl: 'https://recurly.com',
    statusPageUrl: 'https://status.recurly.com',
    relatedDomains: ['recurly.com', '*.recurly.com'],
    searchAliases: ['billing', 'subscriptions'],
  },
  'redhat': {
    name: 'Red Hat',
    type: 'statuspage',
    websiteUrl: 'https://redhat.com',
    statusPageUrl: 'https://status.redhat.com',
    relatedDomains: ['redhat.com', '*.redhat.com', 'quay.io', '*.quay.io', 'openshift.com', '*.openshift.com'],
    searchAliases: ['openshift', 'quay', 'ansible', 'rhel', 'linux', 'container registry'],
  },
  'replicate': {
    name: 'Replicate',
    type: 'statuspage',
    websiteUrl: 'https://replicate.com',
    statusPageUrl: 'https://www.replicatestatus.com',
    relatedDomains: ['replicate.com', '*.replicate.com'],
    searchAliases: ['ai', 'ml', 'machine learning', 'image generation', 'stable diffusion', 'models'],
  },
  'render': {
    name: 'Render',
    type: 'statuspage',
    websiteUrl: 'https://render.com',
    statusPageUrl: 'https://status.render.com',
    relatedDomains: ['render.com', '*.render.com'],
    searchAliases: ['hosting', 'paas', 'deployment', 'static site', 'cron jobs'],
  },
  'replit': {
    name: 'Replit',
    type: 'instatus',
    websiteUrl: 'https://replit.com',
    statusPageUrl: 'https://replit.instatus.com',
    relatedDomains: ['replit.com', '*.replit.com'],
    searchAliases: ['cloud ide', 'coding', 'agent'],
  },
  'resend': {
    name: 'Resend',
    type: 'incidentio',
    websiteUrl: 'https://resend.com',
    statusPageUrl: 'https://resend-status.com',
    relatedDomains: ['resend.com', '*.resend.com'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email api'],
  },
  'retool': {
    name: 'Retool',
    type: 'statuspage',
    websiteUrl: 'https://retool.com',
    statusPageUrl: 'https://status.retool.com',
    relatedDomains: ['retool.com', '*.retool.com'],
    searchAliases: ['internal tools', 'low-code', 'no-code', 'admin panel', 'dashboard builder'],
  },
  'rollbar': {
    name: 'Rollbar',
    type: 'statuspage',
    websiteUrl: 'https://rollbar.com',
    statusPageUrl: 'https://status.rollbar.com',
    relatedDomains: ['rollbar.com', '*.rollbar.com'],
    searchAliases: ['error tracking', 'exceptions', 'crash reporting', 'monitoring', 'debugging'],
  },
  'rubygems': {
    name: 'RubyGems',
    type: 'statuspage',
    websiteUrl: 'https://rubygems.org',
    statusPageUrl: 'https://status.rubygems.org',
    relatedDomains: ['rubygems.org', '*.rubygems.org'],
    searchAliases: ['ruby', 'packages', 'registry', 'gems'],
  },
  'rudderstack': {
    name: 'RudderStack',
    type: 'statuspage',
    websiteUrl: 'https://rudderstack.com',
    statusPageUrl: 'https://status.rudderstack.com',
    relatedDomains: ['rudderstack.com', '*.rudderstack.com'],
    searchAliases: ['cdp', 'events', 'analytics'],
  },
  'sambanova': {
    name: 'SambaNova',
    type: 'statuspage',
    websiteUrl: 'https://sambanova.ai',
    statusPageUrl: 'https://status.sambanova.ai',
    relatedDomains: ['sambanova.ai', '*.sambanova.ai'],
    searchAliases: ['inference', 'llm', 'ai'],
  },
  'sanity': {
    name: 'Sanity',
    type: 'statuspage',
    websiteUrl: 'https://sanity.io',
    statusPageUrl: 'https://www.sanity-status.com',
    relatedDomains: ['sanity.io', '*.sanity.io'],
    searchAliases: ['cms', 'headless cms', 'content management', 'groq', 'studio', 'content lake'],
  },
  'scaleway': {
    name: 'Scaleway',
    type: 'statuspage',
    websiteUrl: 'https://scaleway.com',
    statusPageUrl: 'https://status.scaleway.com',
    relatedDomains: ['scaleway.com', '*.scaleway.com'],
    searchAliases: ['cloud', 'vps', 'hosting', 'europe'],
  },
  'segment': {
    name: 'Segment',
    type: 'statuspage',
    websiteUrl: 'https://segment.com',
    statusPageUrl: 'https://status.segment.com',
    relatedDomains: ['segment.com', '*.segment.com', 'segment.io', '*.segment.io'],
    searchAliases: ['analytics', 'cdp', 'customer data', 'event tracking', 'data pipeline'],
  },
  'semaphore': {
    name: 'Semaphore',
    type: 'statuspage',
    websiteUrl: 'https://semaphoreci.com',
    statusPageUrl: 'https://status.semaphore.io',
    relatedDomains: ['semaphoreci.com', '*.semaphoreci.com', 'semaphore.io', '*.semaphore.io'],
    searchAliases: ['ci', 'pipeline', 'build'],
  },
  'semgrep': {
    name: 'Semgrep',
    type: 'statuspage',
    websiteUrl: 'https://semgrep.dev',
    statusPageUrl: 'https://status.semgrep.dev',
    relatedDomains: ['semgrep.dev', '*.semgrep.dev'],
    searchAliases: ['sast', 'security', 'static analysis'],
  },
  'sendgrid': {
    name: 'SendGrid',
    type: 'statuspage',
    websiteUrl: 'https://sendgrid.com',
    statusPageUrl: 'https://status.sendgrid.com',
    relatedDomains: ['sendgrid.com', '*.sendgrid.com', 'sendgrid.net', '*.sendgrid.net'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email delivery', 'twilio'],
  },
  'sentry': {
    name: 'Sentry',
    type: 'statuspage',
    websiteUrl: 'https://sentry.io',
    statusPageUrl: 'https://status.sentry.io',
    relatedDomains: ['sentry.io', '*.sentry.io'],
    searchAliases: ['error tracking', 'monitoring', 'debugging', 'crash reporting', 'performance'],
  },
  'shortcut': {
    name: 'Shortcut',
    type: 'statuspage',
    websiteUrl: 'https://shortcut.com',
    statusPageUrl: 'https://status.shortcut.com',
    relatedDomains: ['shortcut.com', '*.shortcut.com'],
    searchAliases: ['issue tracker', 'agile', 'project management'],
  },
  'signal': {
    name: 'Signal',
    type: 'signal',
    beta: true,
    websiteUrl: 'https://signal.org',
    statusPageUrl: 'https://status.signal.org',
    relatedDomains: ['signal.org', '*.signal.org', 'signal.me'],
    searchAliases: ['messaging', 'encrypted', 'chat', 'private'],
  },
  'shopify': {
    name: 'Shopify',
    type: 'statuspage',
    websiteUrl: 'https://shopify.com',
    statusPageUrl: 'https://www.shopifystatus.com',
    relatedDomains: ['shopify.com', '*.shopify.com', 'shopifycloud.com'],
    searchAliases: ['ecommerce', 'e-commerce', 'shop', 'store', 'payments', 'checkout'],
  },
  'sinch': {
    name: 'Sinch',
    type: 'statuspage',
    websiteUrl: 'https://sinch.com',
    statusPageUrl: 'https://status.sinch.com',
    relatedDomains: ['sinch.com', '*.sinch.com'],
    searchAliases: ['sms', 'voice', 'messaging'],
  },
  'sketch': {
    name: 'Sketch',
    type: 'instatus',
    websiteUrl: 'https://sketch.com',
    statusPageUrl: 'https://status.sketch.com',
    relatedDomains: ['sketch.com', '*.sketch.com'],
    searchAliases: ['design', 'ui', 'mac'],
  },
  'slack': {
    name: 'Slack',
    type: 'slack',
    websiteUrl: 'https://slack.com',
    statusPageUrl: 'https://slack-status.com',
    relatedDomains: ['slack.com', '*.slack.com'],
    searchAliases: ['messaging', 'chat', 'team communication', 'channels', 'workspace'],
  },
  'smartsheet': {
    name: 'Smartsheet',
    type: 'statuspage',
    websiteUrl: 'https://smartsheet.com',
    statusPageUrl: 'https://status.smartsheet.com',
    relatedDomains: ['smartsheet.com', '*.smartsheet.com'],
    searchAliases: ['spreadsheet', 'project management', 'work'],
  },
  'snowflake': {
    name: 'Snowflake',
    type: 'statuspage',
    websiteUrl: 'https://snowflake.com',
    statusPageUrl: 'https://status.snowflake.com',
    relatedDomains: ['snowflake.com', '*.snowflake.com', '*.snowflakecomputing.com'],
    searchAliases: ['data warehouse', 'cloud database', 'analytics', 'sql', 'data sharing'],
  },
  'snyk': {
    name: 'Snyk',
    type: 'statuspage',
    websiteUrl: 'https://snyk.io',
    statusPageUrl: 'https://status.snyk.io',
    relatedDomains: ['snyk.io', '*.snyk.io'],
    searchAliases: ['security', 'vulnerability', 'sca', 'scanning'],
  },
  'sparkpost': {
    name: 'SparkPost',
    type: 'statuspage',
    websiteUrl: 'https://sparkpost.com',
    statusPageUrl: 'https://status.sparkpost.com',
    relatedDomains: ['sparkpost.com', '*.sparkpost.com', 'messagesystems.com'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email delivery', 'email api'],
  },
  'squarespace': {
    name: 'Squarespace',
    type: 'statuspage',
    websiteUrl: 'https://squarespace.com',
    statusPageUrl: 'https://status.squarespace.com',
    relatedDomains: ['squarespace.com', '*.squarespace.com'],
    searchAliases: ['website builder', 'cms', 'ecommerce'],
  },
  'statuspage': {
    name: 'Statuspage',
    type: 'statuspage',
    websiteUrl: 'https://atlassian.com/software/statuspage',
    statusPageUrl: 'https://metastatuspage.com',
    relatedDomains: ['statuspage.io', '*.statuspage.io'],
    searchAliases: ['status page', 'incident communication', 'atlassian'],
  },
  'stripe': {
    name: 'Stripe',
    type: 'stripe',
    websiteUrl: 'https://stripe.com',
    statusPageUrl: 'https://status.stripe.com',
    relatedDomains: ['stripe.com', '*.stripe.com'],
    searchAliases: ['payments', 'billing', 'subscriptions', 'checkout', 'invoices'],
  },
  'stytch': {
    name: 'Stytch',
    type: 'instatus',
    websiteUrl: 'https://stytch.com',
    statusPageUrl: 'https://status.stytch.com',
    relatedDomains: ['stytch.com', '*.stytch.com'],
    searchAliases: ['authentication', 'auth', 'login', 'passwordless', 'magic link', 'identity'],
  },
  'sumologic': {
    name: 'Sumo Logic',
    type: 'statuspage',
    websiteUrl: 'https://sumologic.com',
    statusPageUrl: 'https://status.sumologic.com',
    relatedDomains: ['sumologic.com', '*.sumologic.com'],
    searchAliases: ['logs', 'siem', 'observability'],
  },
  'supabase': {
    name: 'Supabase',
    type: 'statuspage',
    websiteUrl: 'https://supabase.com',
    statusPageUrl: 'https://status.supabase.com',
    relatedDomains: ['supabase.com', '*.supabase.com', 'supabase.io', 'supabase.co'],
    searchAliases: ['postgres', 'postgresql', 'database', 'firebase alternative', 'auth', 'storage', 'realtime'],
  },
  'supertokens': {
    name: 'SuperTokens',
    type: 'instatus',
    websiteUrl: 'https://supertokens.com',
    statusPageUrl: 'https://supertokens.instatus.com',
    relatedDomains: ['supertokens.com', '*.supertokens.com'],
    searchAliases: ['auth', 'identity', 'session'],
  },
  'tailscale': {
    name: 'Tailscale',
    type: 'statuspage',
    websiteUrl: 'https://tailscale.com',
    statusPageUrl: 'https://status.tailscale.com',
    relatedDomains: ['tailscale.com', '*.tailscale.com'],
    searchAliases: ['vpn', 'networking', 'wireguard', 'mesh network', 'zero trust'],
  },
  'telnyx': {
    name: 'Telnyx',
    type: 'statuspage',
    websiteUrl: 'https://telnyx.com',
    statusPageUrl: 'https://status.telnyx.com',
    relatedDomains: ['telnyx.com', '*.telnyx.com'],
    searchAliases: ['sms', 'voice', 'communications'],
  },
  'temporal': {
    name: 'Temporal',
    type: 'statuspage',
    websiteUrl: 'https://temporal.io',
    statusPageUrl: 'https://status.temporal.io',
    relatedDomains: ['temporal.io', '*.temporal.io'],
    searchAliases: ['workflow', 'orchestration', 'durable execution', 'job queue', 'saga'],
  },
  'tinybird': {
    name: 'Tinybird',
    type: 'incidentio',
    websiteUrl: 'https://tinybird.co',
    statusPageUrl: 'https://status.tinybird.co',
    relatedDomains: ['tinybird.co', '*.tinybird.co'],
    searchAliases: ['analytics', 'real-time analytics', 'data api', 'clickhouse', 'sql', 'streaming'],
  },
  'todoist': {
    name: 'Todoist',
    type: 'instatus',
    websiteUrl: 'https://todoist.com',
    statusPageUrl: 'https://todoist.instatus.com',
    relatedDomains: ['todoist.com', '*.todoist.com'],
    searchAliases: ['tasks', 'todo', 'productivity'],
  },
  'travisci': {
    name: 'Travis CI',
    type: 'statuspage',
    websiteUrl: 'https://travis-ci.com',
    statusPageUrl: 'https://www.traviscistatus.com',
    relatedDomains: ['travis-ci.com', 'travis-ci.org'],
    searchAliases: ['ci', 'continuous integration', 'build', 'pipeline'],
  },
  'trello': {
    name: 'Trello',
    type: 'statuspage',
    websiteUrl: 'https://trello.com',
    statusPageUrl: 'https://trello.status.atlassian.com',
    relatedDomains: ['trello.com', '*.trello.com'],
    searchAliases: ['kanban', 'boards', 'project management'],
  },
  'twilio': {
    name: 'Twilio',
    type: 'statuspage',
    websiteUrl: 'https://twilio.com',
    statusPageUrl: 'https://status.twilio.com',
    relatedDomains: ['twilio.com', '*.twilio.com'],
    searchAliases: ['sms', 'voice', 'messaging', 'phone', 'sendgrid', 'whatsapp', 'video'],
  },
  'twingate': {
    name: 'Twingate',
    type: 'statuspage',
    websiteUrl: 'https://twingate.com',
    statusPageUrl: 'https://status.twingate.com',
    relatedDomains: ['twingate.com', '*.twingate.com'],
    searchAliases: ['zero trust', 'vpn', 'access'],
  },
  'typeform': {
    name: 'Typeform',
    type: 'statuspage',
    websiteUrl: 'https://typeform.com',
    statusPageUrl: 'https://status.typeform.com',
    relatedDomains: ['typeform.com', '*.typeform.com'],
    searchAliases: ['forms', 'surveys', 'questionnaire'],
  },
  'uploadcare': {
    name: 'Uploadcare',
    type: 'statuspage',
    websiteUrl: 'https://uploadcare.com',
    statusPageUrl: 'https://status.uploadcare.com',
    relatedDomains: ['uploadcare.com', '*.uploadcare.com'],
    searchAliases: ['file upload', 'cdn', 'images'],
  },
  'upstash': {
    name: 'Upstash',
    type: 'statuspage',
    websiteUrl: 'https://upstash.com',
    statusPageUrl: 'https://status.upstash.com',
    relatedDomains: ['upstash.com', '*.upstash.com'],
    searchAliases: ['redis', 'kafka', 'serverless', 'database', 'cache', 'qstash'],
  },
  'vectara': {
    name: 'Vectara',
    type: 'statuspage',
    websiteUrl: 'https://vectara.com',
    statusPageUrl: 'https://status.vectara.com',
    relatedDomains: ['vectara.com', '*.vectara.com'],
    searchAliases: ['vector search', 'rag', 'ai'],
  },
  'vercel': {
    name: 'Vercel',
    type: 'statuspage',
    websiteUrl: 'https://vercel.com',
    statusPageUrl: 'https://www.vercel-status.com',
    relatedDomains: ['vercel.com', '*.vercel.com'],
    searchAliases: ['hosting', 'nextjs', 'next.js', 'deployment', 'frontend', 'edge', 'serverless'],
  },
  'vespa': {
    name: 'Vespa',
    type: 'instatus',
    websiteUrl: 'https://vespa.ai',
    statusPageUrl: 'https://status.vespa.ai',
    relatedDomains: ['vespa.ai', '*.vespa.ai'],
    searchAliases: ['search', 'vector', 'serving'],
  },
  'vimeo': {
    name: 'Vimeo',
    type: 'statuspage',
    websiteUrl: 'https://vimeo.com',
    statusPageUrl: 'https://www.vimeostatus.com',
    relatedDomains: ['vimeo.com', '*.vimeo.com'],
    searchAliases: ['video', 'hosting', 'streaming'],
  },
  'webflow': {
    name: 'Webflow',
    type: 'statuspage',
    websiteUrl: 'https://webflow.com',
    statusPageUrl: 'https://status.webflow.com',
    relatedDomains: ['webflow.com', '*.webflow.com'],
    searchAliases: ['cms', 'website builder', 'no-code'],
  },
  'whereby': {
    name: 'Whereby',
    type: 'instatus',
    websiteUrl: 'https://whereby.com',
    statusPageUrl: 'https://whereby.instatus.com',
    relatedDomains: ['whereby.com', '*.whereby.com'],
    searchAliases: ['video', 'meetings', 'webrtc'],
  },
  'windsurf': {
    name: 'Windsurf',
    type: 'statuspage',
    websiteUrl: 'https://windsurf.com',
    statusPageUrl: 'https://status.windsurf.com',
    relatedDomains: ['windsurf.com', '*.windsurf.com'],
    searchAliases: ['ide', 'codeium', 'ai coding'],
  },
  'wistia': {
    name: 'Wistia',
    type: 'instatus',
    websiteUrl: 'https://wistia.com',
    statusPageUrl: 'https://status.wistia.com',
    relatedDomains: ['wistia.com', '*.wistia.com'],
    searchAliases: ['video', 'hosting', 'marketing'],
  },
  'workos': {
    name: 'WorkOS',
    type: 'statuspage',
    websiteUrl: 'https://workos.com',
    statusPageUrl: 'https://status.workos.com',
    relatedDomains: ['workos.com', '*.workos.com'],
    searchAliases: ['sso', 'saml', 'enterprise auth', 'directory sync', 'scim', 'identity', 'authentication'],
  },
  'writer': {
    name: 'Writer',
    type: 'statuspage',
    websiteUrl: 'https://writer.com',
    statusPageUrl: 'https://writer.statuspage.io',
    relatedDomains: ['writer.com', '*.writer.com'],
    searchAliases: ['llm', 'ai', 'enterprise'],
  },
  'yousign': {
    name: 'YouSign',
    type: 'statuspage',
    websiteUrl: 'https://yousign.com',
    statusPageUrl: 'https://yousign.statuspage.io',
    relatedDomains: ['yousign.com', '*.yousign.com', 'yousign.app', '*.yousign.app'],
    searchAliases: ['e-signature', 'esign', 'signature', 'document', 'contract', 'sign'],
  },
  'zapier': {
    name: 'Zapier',
    type: 'incidentio',
    websiteUrl: 'https://zapier.com',
    statusPageUrl: 'https://status.zapier.com',
    relatedDomains: ['zapier.com', '*.zapier.com'],
    searchAliases: ['automation', 'workflow', 'integration', 'zap', 'no-code'],
  },
  'zendesk': {
    name: 'Zendesk',
    type: 'zendesk',
    websiteUrl: 'https://zendesk.com',
    statusPageUrl: 'https://status.zendesk.com',
    relatedDomains: ['zendesk.com', '*.zendesk.com', 'zdassets.com'],
    searchAliases: ['customer support', 'helpdesk', 'tickets', 'crm', 'live chat'],
  },
  'zilliz': {
    name: 'Zilliz',
    type: 'statuspage',
    websiteUrl: 'https://zilliz.com',
    statusPageUrl: 'https://status.zilliz.com',
    relatedDomains: ['zilliz.com', '*.zilliz.com'],
    searchAliases: ['vector database', 'milvus', 'embeddings'],
  },
  'zitadel': {
    name: 'Zitadel',
    type: 'statuspage',
    websiteUrl: 'https://zitadel.com',
    statusPageUrl: 'https://status.zitadel.com',
    relatedDomains: ['zitadel.com', '*.zitadel.com'],
    searchAliases: ['auth', 'identity', 'oidc'],
  },
  'zoho': {
    name: 'Zoho',
    type: 'site24x7',
    websiteUrl: 'https://zoho.com',
    statusPageUrl: 'https://status.zoho.com',
    relatedDomains: ['zoho.com', '*.zoho.com', 'zohopublic.com', '*.zohopublic.com'],
    searchAliases: ['crm', 'zoho mail', 'zoho docs', 'zoho books', 'zoho desk', 'zoho projects', 'zoho campaigns'],
  },
  'zoom': {
    name: 'Zoom',
    type: 'statuspage',
    websiteUrl: 'https://zoom.us',
    statusPageUrl: 'https://status.zoom.us',
    relatedDomains: ['zoom.us', '*.zoom.us'],
    searchAliases: ['video', 'conferencing', 'meetings', 'webinar', 'video call'],
  },
};
