// Built-in catalog of services.
//
// type (required):
//   "algolia"      — Algolia custom API; polls /3/public/availability.
//   "auth0"        — Auth0 custom Next.js page; extracts buildId from HTML then
//                    fetches /_next/data/{buildId}/index.json for region status.
//   "awshealth"    — AWS Service Health Dashboard; polls /public/currentevents (UTF-16 encoded).
//   "cachet"       — CachetHQ status pages; polls /components and /incidents (JSON:API).
//   "google"       — Google incident dashboard format (used by Google Workspace and Google Cloud);
//                    polls /incidents.json + /products.json and derives status from active incidents
//                    (those with no `end` field).
//   "heroku"       — Heroku custom API; polls /api/v4/current-status.
//   "hund"         — Hund.io status pages; reads the first SSE init_event from /live/v2/status_page.
//   "incidentio"   — incident.io status pages; exposes the same /api/v2 endpoints as Statuspage.io,
//                    so the same fetcher handles both.
//   "instatus"     — Instatus-hosted status pages; polls /api/v2/summary.json and
//                    /api/v2/components.json. No public incidents endpoint available.
//   "pagerduty"    — PagerDuty status page product; polls /api/services and /api/posts.
//   "posthog"      — PostHog custom Next.js status page; polls /api/status.
//   "signal"       — Signal's hand-rolled HTML page; no API. Scrapes text for "up and running".
//                    Beta — fragile if Signal changes their wording.
//   "site24x7"     — StatusIQ (Zoho/Site24x7); polls /sp/api/u/summary_details.
//   "slack"        — Slack's custom status API at /api/v1.0.0/current.
//   "sorryapp"     — SorryApp platform; polls /api/v1/status, /api/v1/components, /api/v1/notices.
//   "statuscast"   — StatusCast platform; polls /status.json, /components.json, /incidents.json.
//                    Requires a browser User-Agent (bot filter).
//   "statusio"     — status.io pages; single endpoint at api.status.io/1.0/status/{pageId}.
//                    Requires a `pageId` field on the catalog entry.
//   "statuspage"   — Atlassian Statuspage.io, uses /api/v2 endpoints.
//   "stripe"       — Stripe custom status page; polls /current/full.
//   "uptimerobot"  — UptimeRobot status pages; uses /api/getMonitorList/x.
//   "zendesk"      — Zendesk custom JSON:API; polls /api/ssp/services.json and
//                    /api/ssp/incidents.json?as_of_date={date}.
//
// searchAliases: additional keywords matched when the user types in the catalog search box.
//   Use this for well-known product names that aren't part of the service name
//   (e.g. "jira", "gmail", "chatgpt"). All lowercase; matched as substrings.
//
// relatedDomains: product/app domains for this service.
//   Patterns starting with "*." match that domain and all its subdomains.
//   Used to suggest adding a service when the user visits a related page
//   (e.g. visiting claude.ai suggests tracking status.claude.com).
//
// Intentionally excluded from wildcards: user-content hosts such as
//   *.github.io, *.vercel.app, *.netlify.app, *.myshopify.com, *.onrender.com
const CATALOG = {
  '1password': {
    name: '1Password',
    type: 'statuspage',
    pageUrl: 'https://status.1password.com',
    apiBase: 'https://status.1password.com/api/v2',
    relatedDomains: ['1password.com', '*.1password.com'],
    searchAliases: ['password manager', 'secrets', 'vault', 'security'],
  },
  'airtable': {
    name: 'Airtable',
    type: 'statuspage',
    pageUrl: 'https://status.airtable.com',
    apiBase: 'https://status.airtable.com/api/v2',
    relatedDomains: ['airtable.com', '*.airtable.com'],
    searchAliases: ['database', 'spreadsheet', 'no-code', 'base', 'grid'],
  },
  'algolia': {
    name: 'Algolia',
    type: 'algolia',
    pageUrl: 'https://status.algolia.com',
    apiBase: 'https://status.algolia.com',
    relatedDomains: ['algolia.com', '*.algolia.com', 'algolia.net', '*.algolia.net'],
    searchAliases: ['search', 'autocomplete', 'instant search', 'indexing'],
  },
  'atlassian': {
    name: 'Atlassian',
    type: 'statuspage',
    pageUrl: 'https://status.atlassian.com',
    apiBase: 'https://status.atlassian.com/api/v2',
    relatedDomains: [
      'atlassian.com', '*.atlassian.com',
      'atlassian.net', '*.atlassian.net',
      'jira.com', '*.jira.com',
      'trello.com', '*.trello.com',
      'confluence.com',
    ],
    searchAliases: ['jira', 'confluence', 'trello', 'bitbucket', 'opsgenie', 'statuspage', 'loom', 'issues', 'project management'],
  },
  'auth0': {
    name: 'Auth0',
    type: 'auth0',
    pageUrl: 'https://status.auth0.com',
    apiBase: 'https://status.auth0.com',
    relatedDomains: ['auth0.com', '*.auth0.com', 'okta.com', '*.okta.com'],
    searchAliases: ['okta', 'authentication', 'identity', 'login', 'sso', 'oauth'],
  },
  'aws-health': {
    name: 'AWS Health',
    type: 'awshealth',
    beta: true,
    pageUrl: 'https://health.aws.com/health/status',
    apiBase: 'https://health.aws.amazon.com',
    relatedDomains: ['aws.amazon.com', 'console.aws.amazon.com', 'health.aws.com'],
    searchAliases: ['amazon', 'amazon web services', 'ec2', 's3', 'lambda', 'rds', 'cloudfront', 'dynamodb', 'eks', 'ecs', 'cloudwatch'],
  },
  'bitwarden': {
    name: 'Bitwarden',
    type: 'hund',
    pageUrl: 'https://status.bitwarden.com',
    apiBase: 'https://status.bitwarden.com',
    relatedDomains: ['bitwarden.com', '*.bitwarden.com'],
    searchAliases: ['password manager', 'passwords', 'vault', 'security'],
  },
  'circleci': {
    name: 'CircleCI',
    type: 'statuspage',
    pageUrl: 'https://status.circleci.com',
    apiBase: 'https://status.circleci.com/api/v2',
    relatedDomains: ['circleci.com', '*.circleci.com'],
    searchAliases: ['ci', 'cd', 'ci/cd', 'continuous integration', 'pipeline', 'build'],
  },
  'claude': {
    name: 'Claude',
    type: 'statuspage',
    pageUrl: 'https://status.claude.com',
    apiBase: 'https://status.claude.com/api/v2',
    relatedDomains: ['claude.ai', '*.claude.ai', 'anthropic.com', '*.anthropic.com'],
    searchAliases: ['anthropic', 'ai', 'llm', 'chatbot'],
  },
  'clever-cloud': {
    name: 'Clever Cloud',
    type: 'cachet',
    beta: true,
    pageUrl: 'https://www.clevercloudstatus.com',
    apiBase: 'https://www.clevercloudstatus.com/api',
    relatedDomains: ['clever-cloud.com', '*.clever-cloud.com'],
    searchAliases: ['paas', 'cloud', 'hosting', 'deployment', 'scaleway'],
  },
  'cloudflare': {
    name: 'Cloudflare',
    type: 'statuspage',
    pageUrl: 'https://www.cloudflarestatus.com',
    apiBase: 'https://www.cloudflarestatus.com/api/v2',
    relatedDomains: ['cloudflare.com', '*.cloudflare.com'],
    searchAliases: ['cdn', 'dns', 'workers', 'pages', 'waf', 'ddos', 'tunnel', 'r2'],
  },
  'cloudinary': {
    name: 'Cloudinary',
    type: 'statuspage',
    pageUrl: 'https://status.cloudinary.com',
    apiBase: 'https://status.cloudinary.com/api/v2',
    relatedDomains: ['cloudinary.com', '*.cloudinary.com'],
    searchAliases: ['images', 'media', 'cdn', 'video', 'image optimization', 'upload'],
  },
  'configcat': {
    name: 'ConfigCat',
    type: 'site24x7',
    pageUrl: 'https://status.configcat.com',
    apiBase: 'https://status.configcat.com',
    relatedDomains: ['configcat.com', '*.configcat.com'],
    searchAliases: ['feature flags', 'feature toggles', 'feature management', 'a/b testing'],
  },
  'cursor': {
    name: 'Cursor',
    type: 'statuspage',
    pageUrl: 'https://status.cursor.com',
    apiBase: 'https://status.cursor.com/api/v2',
    relatedDomains: ['cursor.com', '*.cursor.com'],
    searchAliases: ['ide', 'code editor', 'ai coding', 'copilot'],
  },
  'dashdoc': {
    name: 'Dashdoc',
    type: 'incidentio',
    pageUrl: 'https://www.dashdocstatus.com',
    apiBase: 'https://www.dashdocstatus.com/api/v2',
    relatedDomains: ['dashdoc.eu', '*.dashdoc.eu', 'dashdoc.com', '*.dashdoc.com'],
    searchAliases: ['transport', 'tms', 'logistics', 'freight', 'trucking'],
  },
  'dashlane': {
    name: 'Dashlane',
    type: 'statusio',
    pageUrl: 'https://status.dashlane.com',
    apiBase: 'https://api.status.io/1.0',
    pageId:  '5aabcb89fccc4b04d3774443',
    relatedDomains: ['dashlane.com', '*.dashlane.com'],
    searchAliases: ['password manager', 'passwords', 'vault', 'security'],
  },
  'datadog': {
    name: 'Datadog',
    type: 'statuspage',
    pageUrl: 'https://status.datadoghq.com',
    apiBase: 'https://status.datadoghq.com/api/v2',
    relatedDomains: ['datadoghq.com', '*.datadoghq.com'],
    searchAliases: ['monitoring', 'apm', 'logs', 'observability', 'metrics', 'infrastructure'],
  },
  'digitalocean': {
    name: 'DigitalOcean',
    type: 'statuspage',
    pageUrl: 'https://status.digitalocean.com',
    apiBase: 'https://status.digitalocean.com/api/v2',
    relatedDomains: ['digitalocean.com', '*.digitalocean.com'],
    searchAliases: ['cloud', 'droplet', 'vps', 'kubernetes', 'spaces', 'managed database'],
  },
  'discord': {
    name: 'Discord',
    type: 'statuspage',
    pageUrl: 'https://discordstatus.com',
    apiBase: 'https://discordstatus.com/api/v2',
    relatedDomains: ['discord.com', '*.discord.com', 'discordapp.com'],
    searchAliases: ['chat', 'gaming', 'community', 'voice', 'server', 'bot'],
  },
  'docker': {
    name: 'Docker',
    type: 'statusio',
    pageUrl: 'https://www.dockerstatus.com',
    apiBase: 'https://api.status.io/1.0',
    pageId:  '533c6539221ae15e3f000031',
    relatedDomains: ['docker.com', '*.docker.com', 'dockerhub.com'],
    searchAliases: ['containers', 'hub', 'registry', 'dockerfile', 'compose'],
  },
  'docusign': {
    name: 'DocuSign',
    type: 'statuspage',
    pageUrl: 'https://status.docusign.com',
    apiBase: 'https://status.docusign.com/api/v2',
    relatedDomains: ['docusign.com', '*.docusign.com', 'docusign.net', '*.docusign.net'],
    searchAliases: ['e-signature', 'esign', 'document signing', 'contracts'],
  },
  'dropbox': {
    name: 'Dropbox',
    type: 'statuspage',
    pageUrl: 'https://status.dropbox.com',
    apiBase: 'https://status.dropbox.com/api/v2',
    relatedDomains: ['dropbox.com', '*.dropbox.com', 'dropboxbusiness.com'],
    searchAliases: ['file storage', 'cloud storage', 'sync', 'file sharing'],
  },
  'fastly': {
    name: 'Fastly',
    type: 'statuscast',
    pageUrl: 'https://www.fastlystatus.com',
    apiBase: 'https://www.fastlystatus.com',
    relatedDomains: ['fastly.com', '*.fastly.com', 'fastly.net', '*.fastly.net'],
    searchAliases: ['cdn', 'edge', 'cache', 'waf', 'streaming'],
  },
  'figma': {
    name: 'Figma',
    type: 'statuspage',
    pageUrl: 'https://status.figma.com',
    apiBase: 'https://status.figma.com/api/v2',
    relatedDomains: ['figma.com', '*.figma.com'],
    searchAliases: ['design', 'prototyping', 'ui', 'ux', 'wireframe'],
  },
  'flyio': {
    name: 'Fly.io',
    type: 'statuspage',
    pageUrl: 'https://status.flyio.net',
    apiBase: 'https://status.flyio.net/api/v2',
    relatedDomains: ['fly.io', '*.fly.io'],
    searchAliases: ['hosting', 'deployment', 'containers', 'paas'],
  },
  'github': {
    name: 'GitHub',
    type: 'statuspage',
    pageUrl: 'https://www.githubstatus.com',
    apiBase: 'https://www.githubstatus.com/api/v2',
    relatedDomains: ['github.com', '*.github.com'],
    searchAliases: ['git', 'repos', 'actions', 'copilot', 'packages', 'pages', 'gist', 'pull request'],
  },
  'gitlab': {
    name: 'GitLab',
    type: 'statusio',
    pageUrl: 'https://status.gitlab.com',
    apiBase: 'https://api.status.io/1.0',
    pageId:  '5b36dc6502d06804c08349f7',
    relatedDomains: ['gitlab.com', '*.gitlab.com'],
    searchAliases: ['git', 'ci/cd', 'devops', 'repos', 'pipeline', 'merge request'],
  },
  'google-cloud': {
    name: 'Google Cloud',
    type: 'google',
    pageUrl: 'https://status.cloud.google.com',
    apiBase: 'https://status.cloud.google.com',
    relatedDomains: [
      'cloud.google.com', 'googleapis.com', '*.googleapis.com',
      'googlecloud.com', '*.googlecloud.com',
    ],
    searchAliases: ['gcp', 'gce', 'gke', 'bigquery', 'firebase', 'compute engine', 'cloud run', 'cloud functions', 'pubsub', 'spanner', 'gemini', 'vertex ai', 'vertex', 'ai studio', 'gemini api', 'gemini code assist'],
  },
  'google-workspace': {
    name: 'Google Workspace',
    type: 'google',
    pageUrl: 'https://www.google.com/appsstatus/dashboard',
    apiBase: 'https://www.google.com/appsstatus/dashboard',
    relatedDomains: [
      'workspace.google.com',
      'gmail.com', 'drive.google.com', 'docs.google.com',
      'sheets.google.com', 'slides.google.com', 'meet.google.com',
      'calendar.google.com', 'chat.google.com', 'mail.google.com',
    ],
    searchAliases: ['gmail', 'google drive', 'google docs', 'google sheets', 'google meet', 'google calendar', 'google chat', 'g suite', 'gsuite', 'google mail'],
  },
  'grafana': {
    name: 'Grafana',
    type: 'statuspage',
    pageUrl: 'https://status.grafana.com',
    apiBase: 'https://status.grafana.com/api/v2',
    relatedDomains: ['grafana.com', '*.grafana.com', 'grafana.net', '*.grafana.net'],
    searchAliases: ['monitoring', 'dashboards', 'prometheus', 'loki', 'mimir', 'tempo', 'observability'],
  },
  'harvest': {
    name: 'Harvest',
    type: 'statuspage',
    pageUrl: 'https://www.harveststatus.com',
    apiBase: 'https://www.harveststatus.com/api/v2',
    relatedDomains: ['harvestapp.com', '*.harvestapp.com', 'getharvest.com', '*.getharvest.com'],
    searchAliases: ['time tracking', 'invoicing', 'timesheets', 'billing'],
  },
  'hasura': {
    name: 'Hasura',
    type: 'incidentio',
    pageUrl: 'https://hasura-status.com',
    apiBase: 'https://hasura-status.com/api/v2',
    relatedDomains: ['hasura.io', '*.hasura.io'],
    searchAliases: ['graphql', 'database', 'api', 'postgres'],
  },
  'heroku': {
    name: 'Heroku',
    type: 'heroku',
    pageUrl: 'https://status.heroku.com',
    apiBase: 'https://status.heroku.com',
    relatedDomains: ['heroku.com', '*.heroku.com', 'herokuapp.com'],
    searchAliases: ['paas', 'hosting', 'deployment', 'dyno', 'salesforce'],
  },
  'hubspot': {
    name: 'HubSpot',
    type: 'statuspage',
    pageUrl: 'https://status.hubspot.com',
    apiBase: 'https://status.hubspot.com/api/v2',
    relatedDomains: ['hubspot.com', '*.hubspot.com', 'hubspotusercontent.com'],
    searchAliases: ['crm', 'marketing', 'sales', 'email marketing', 'automation'],
  },
  'intercom': {
    name: 'Intercom',
    type: 'statuspage',
    pageUrl: 'https://www.intercomstatus.com',
    apiBase: 'https://www.intercomstatus.com/api/v2',
    relatedDomains: ['intercom.com', '*.intercom.com', 'intercom.io', '*.intercom.io'],
    searchAliases: ['customer support', 'chat', 'messaging', 'helpdesk', 'live chat'],
  },
  'launchdarkly': {
    name: 'LaunchDarkly',
    type: 'statuspage',
    pageUrl: 'https://status.launchdarkly.com',
    apiBase: 'https://status.launchdarkly.com/api/v2',
    relatedDomains: ['launchdarkly.com', '*.launchdarkly.com'],
    searchAliases: ['feature flags', 'feature toggles', 'feature management', 'a/b testing'],
  },
  'linear': {
    name: 'Linear',
    type: 'incidentio',
    pageUrl: 'https://linearstatus.com',
    apiBase: 'https://linearstatus.com/api/v2',
    relatedDomains: ['linear.app', '*.linear.app'],
    searchAliases: ['project management', 'issues', 'tickets', 'sprint', 'roadmap'],
  },
  'loom': {
    name: 'Loom',
    type: 'statuspage',
    pageUrl: 'https://loom.status.atlassian.com',
    apiBase: 'https://loom.status.atlassian.com/api/v2',
    relatedDomains: ['loom.com', '*.loom.com'],
    searchAliases: ['video', 'screen recording', 'async video', 'screen capture'],
  },
  'manageengine': {
    name: 'ManageEngine',
    type: 'site24x7',
    pageUrl: 'https://status.manageengine.com',
    apiBase: 'https://status.manageengine.com',
    relatedDomains: ['manageengine.com', '*.manageengine.com'],
    searchAliases: ['it management', 'helpdesk', 'service desk', 'endpoint management', 'patch management', 'ad manager'],
  },
  'mastodon': {
    name: 'Mastodon Social',
    type: 'instatus',
    pageUrl: 'https://status.mastodon.social',
    apiBase: 'https://status.mastodon.social/api/v2',
    relatedDomains: ['mastodon.social', '*.mastodon.social'],
    searchAliases: ['fediverse', 'activitypub', 'microblogging', 'social media'],
  },
  'metabase': {
    name: 'Metabase',
    type: 'statuspage',
    pageUrl: 'https://status.metabase.com',
    apiBase: 'https://status.metabase.com/api/v2',
    relatedDomains: ['metabase.com', '*.metabase.com'],
    searchAliases: ['business intelligence', 'bi', 'analytics', 'dashboards', 'data visualization'],
  },
  'miro': {
    name: 'Miro',
    type: 'incidentio',
    pageUrl: 'https://status.miro.com',
    apiBase: 'https://status.miro.com/api/v2',
    relatedDomains: ['miro.com', '*.miro.com'],
    searchAliases: ['whiteboard', 'collaboration', 'design', 'mind map', 'brainstorming'],
  },
  'mongodb': {
    name: 'MongoDB Atlas',
    type: 'statuspage',
    pageUrl: 'https://status.mongodb.com',
    apiBase: 'https://status.mongodb.com/api/v2',
    relatedDomains: ['mongodb.com', '*.mongodb.com', 'mongodb.net', '*.mongodb.net'],
    searchAliases: ['mongodb', 'database', 'nosql', 'atlas', 'document store'],
  },
  'neon': {
    name: 'Neon',
    type: 'statusio',
    pageUrl: 'https://neonstatus.com',
    apiBase: 'https://api.status.io/1.0',
    pageId:  '6878fc85709daa75be6c7e3c',
    relatedDomains: ['neon.tech', '*.neon.tech'],
    searchAliases: ['postgres', 'postgresql', 'serverless', 'database', 'branching'],
  },
  'netlify': {
    name: 'Netlify',
    type: 'statuspage',
    pageUrl: 'https://netlifystatus.com',
    apiBase: 'https://netlifystatus.com/api/v2',
    relatedDomains: ['netlify.com', '*.netlify.com'],
    searchAliases: ['hosting', 'jamstack', 'deployment', 'static site', 'frontend', 'edge functions'],
  },
  'newrelic': {
    name: 'New Relic',
    type: 'statuspage',
    pageUrl: 'https://status.newrelic.com',
    apiBase: 'https://status.newrelic.com/api/v2',
    relatedDomains: ['newrelic.com', '*.newrelic.com'],
    searchAliases: ['monitoring', 'apm', 'observability', 'logs', 'metrics', 'tracing'],
  },
  'notion': {
    name: 'Notion',
    type: 'statuspage',
    pageUrl: 'https://www.notion-status.com',
    apiBase: 'https://www.notion-status.com/api/v2',
    relatedDomains: ['notion.so', '*.notion.so', 'notion.com', '*.notion.com'],
    searchAliases: ['notes', 'wiki', 'docs', 'workspace', 'knowledge base', 'database'],
  },
  'npm': {
    name: 'npm',
    type: 'statuspage',
    pageUrl: 'https://status.npmjs.org',
    apiBase: 'https://status.npmjs.org/api/v2',
    relatedDomains: ['npmjs.com', 'npmjs.org', 'npm.com'],
    searchAliases: ['node', 'nodejs', 'package manager', 'registry', 'javascript', 'packages'],
  },
  'openai': {
    name: 'OpenAI',
    type: 'incidentio',
    pageUrl: 'https://status.openai.com',
    apiBase: 'https://status.openai.com/api/v2',
    relatedDomains: ['openai.com', '*.openai.com', 'chatgpt.com', '*.chatgpt.com'],
    searchAliases: ['chatgpt', 'gpt', 'gpt-4', 'ai', 'llm', 'dall-e', 'whisper'],
  },
  'packagist': {
    name: 'Packagist',
    type: 'uptimerobot',
    pageUrl: 'https://status.packagist.org',
    apiBase: 'https://status.packagist.org/api',
    relatedDomains: ['packagist.org', '*.packagist.org'],
    searchAliases: ['php', 'composer', 'package manager', 'registry'],
  },
  'pagerduty': {
    name: 'PagerDuty',
    type: 'pagerduty',
    pageUrl: 'https://status.pagerduty.com',
    apiBase: 'https://status.pagerduty.com',
    relatedDomains: ['pagerduty.com', '*.pagerduty.com'],
    searchAliases: ['on-call', 'alerting', 'incident management', 'ops', 'devops'],
  },
  'pandadoc': {
    name: 'PandaDoc',
    type: 'statuspage',
    pageUrl: 'https://status.pandadoc.com',
    apiBase: 'https://status.pandadoc.com/api/v2',
    relatedDomains: ['pandadoc.com', '*.pandadoc.com'],
    searchAliases: ['e-signature', 'esign', 'proposals', 'contracts', 'documents'],
  },
  'plaid': {
    name: 'Plaid',
    type: 'statuspage',
    pageUrl: 'https://status.plaid.com',
    apiBase: 'https://status.plaid.com/api/v2',
    relatedDomains: ['plaid.com', '*.plaid.com'],
    searchAliases: ['fintech', 'banking', 'open banking', 'financial data', 'bank connection'],
  },
  'planetscale': {
    name: 'PlanetScale',
    type: 'statuspage',
    pageUrl: 'https://www.planetscalestatus.com',
    apiBase: 'https://www.planetscalestatus.com/api/v2',
    relatedDomains: ['planetscale.com', '*.planetscale.com'],
    searchAliases: ['mysql', 'database', 'serverless db', 'vitess'],
  },
  'posthog': {
    name: 'PostHog',
    type: 'posthog',
    pageUrl: 'https://www.posthogstatus.com',
    apiBase: 'https://www.posthogstatus.com',
    relatedDomains: ['posthog.com', '*.posthog.com'],
    searchAliases: ['analytics', 'product analytics', 'feature flags', 'session recording', 'funnels'],
  },
  'postmark': {
    name: 'Postmark',
    type: 'sorryapp',
    pageUrl: 'https://status.postmarkapp.com',
    apiBase: 'https://status.postmarkapp.com',
    relatedDomains: ['postmarkapp.com', '*.postmarkapp.com'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email delivery'],
  },
  'proton': {
    name: 'Proton',
    type: 'statuspage',
    pageUrl: 'https://status.proton.me',
    apiBase: 'https://status.proton.me/api/v2',
    relatedDomains: ['proton.me', '*.proton.me', 'protonmail.com', '*.protonmail.com', 'protonvpn.com'],
    searchAliases: ['protonmail', 'proton vpn', 'proton drive', 'email', 'privacy', 'encrypted'],
  },
  'python': {
    name: 'Python Infrastructure',
    type: 'statuspage',
    pageUrl: 'https://status.python.org',
    apiBase: 'https://status.python.org/api/v2',
    relatedDomains: ['python.org', '*.python.org', 'pypi.org', '*.pypi.org'],
    searchAliases: ['pypi', 'pip', 'python'],
  },
  'render': {
    name: 'Render',
    type: 'statuspage',
    pageUrl: 'https://status.render.com',
    apiBase: 'https://status.render.com/api/v2',
    relatedDomains: ['render.com', '*.render.com'],
    searchAliases: ['hosting', 'paas', 'deployment', 'static site', 'cron jobs'],
  },
  'resend': {
    name: 'Resend',
    type: 'incidentio',
    pageUrl: 'https://resend-status.com',
    apiBase: 'https://resend-status.com/api/v2',
    relatedDomains: ['resend.com', '*.resend.com'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email api'],
  },
  'segment': {
    name: 'Segment',
    type: 'statuspage',
    pageUrl: 'https://status.segment.com',
    apiBase: 'https://status.segment.com/api/v2',
    relatedDomains: ['segment.com', '*.segment.com', 'segment.io', '*.segment.io'],
    searchAliases: ['analytics', 'cdp', 'customer data', 'event tracking', 'data pipeline'],
  },
  'sendgrid': {
    name: 'SendGrid',
    type: 'statuspage',
    pageUrl: 'https://status.sendgrid.com',
    apiBase: 'https://status.sendgrid.com/api/v2',
    relatedDomains: ['sendgrid.com', '*.sendgrid.com', 'sendgrid.net', '*.sendgrid.net'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email delivery', 'twilio'],
  },
  'sentry': {
    name: 'Sentry',
    type: 'statuspage',
    pageUrl: 'https://status.sentry.io',
    apiBase: 'https://status.sentry.io/api/v2',
    relatedDomains: ['sentry.io', '*.sentry.io'],
    searchAliases: ['error tracking', 'monitoring', 'debugging', 'crash reporting', 'performance'],
  },
  'signal': {
    name: 'Signal',
    type: 'signal',
    beta: true,
    pageUrl: 'https://status.signal.org',
    apiBase: 'https://status.signal.org',
    relatedDomains: ['signal.org', '*.signal.org', 'signal.me'],
    searchAliases: ['messaging', 'encrypted', 'chat', 'private'],
  },
  'shopify': {
    name: 'Shopify',
    type: 'statuspage',
    pageUrl: 'https://www.shopifystatus.com',
    apiBase: 'https://www.shopifystatus.com/api/v2',
    relatedDomains: ['shopify.com', '*.shopify.com', 'shopifycloud.com'],
    searchAliases: ['ecommerce', 'e-commerce', 'shop', 'store', 'payments', 'checkout'],
  },
  'slack': {
    name: 'Slack',
    type: 'slack',
    pageUrl: 'https://slack-status.com',
    apiBase: 'https://slack-status.com/api/v1.0.0',
    relatedDomains: ['slack.com', '*.slack.com'],
    searchAliases: ['messaging', 'chat', 'team communication', 'channels', 'workspace'],
  },
  'snowflake': {
    name: 'Snowflake',
    type: 'statuspage',
    pageUrl: 'https://status.snowflake.com',
    apiBase: 'https://status.snowflake.com/api/v2',
    relatedDomains: ['snowflake.com', '*.snowflake.com', '*.snowflakecomputing.com'],
    searchAliases: ['data warehouse', 'cloud database', 'analytics', 'sql', 'data sharing'],
  },
  'stripe': {
    name: 'Stripe',
    type: 'stripe',
    pageUrl: 'https://status.stripe.com',
    apiBase: 'https://status.stripe.com',
    relatedDomains: ['stripe.com', '*.stripe.com'],
    searchAliases: ['payments', 'billing', 'subscriptions', 'checkout', 'invoices'],
  },
  'supabase': {
    name: 'Supabase',
    type: 'statuspage',
    pageUrl: 'https://status.supabase.com',
    apiBase: 'https://status.supabase.com/api/v2',
    relatedDomains: ['supabase.com', '*.supabase.com', 'supabase.io', 'supabase.co'],
    searchAliases: ['postgres', 'postgresql', 'database', 'firebase alternative', 'auth', 'storage', 'realtime'],
  },
  'tailscale': {
    name: 'Tailscale',
    type: 'statuspage',
    pageUrl: 'https://status.tailscale.com',
    apiBase: 'https://status.tailscale.com/api/v2',
    relatedDomains: ['tailscale.com', '*.tailscale.com'],
    searchAliases: ['vpn', 'networking', 'wireguard', 'mesh network', 'zero trust'],
  },
  'travisci': {
    name: 'Travis CI',
    type: 'statuspage',
    pageUrl: 'https://www.traviscistatus.com',
    apiBase: 'https://www.traviscistatus.com/api/v2',
    relatedDomains: ['travis-ci.com', 'travis-ci.org'],
    searchAliases: ['ci', 'continuous integration', 'build', 'pipeline'],
  },
  'twilio': {
    name: 'Twilio',
    type: 'statuspage',
    pageUrl: 'https://status.twilio.com',
    apiBase: 'https://status.twilio.com/api/v2',
    relatedDomains: ['twilio.com', '*.twilio.com'],
    searchAliases: ['sms', 'voice', 'messaging', 'phone', 'sendgrid', 'whatsapp', 'video'],
  },
  'upstash': {
    name: 'Upstash',
    type: 'statuspage',
    pageUrl: 'https://status.upstash.com',
    apiBase: 'https://status.upstash.com/api/v2',
    relatedDomains: ['upstash.com', '*.upstash.com'],
    searchAliases: ['redis', 'kafka', 'serverless', 'database', 'cache', 'qstash'],
  },
  'vercel': {
    name: 'Vercel',
    type: 'statuspage',
    pageUrl: 'https://www.vercel-status.com',
    apiBase: 'https://www.vercel-status.com/api/v2',
    relatedDomains: ['vercel.com', '*.vercel.com'],
    searchAliases: ['hosting', 'nextjs', 'next.js', 'deployment', 'frontend', 'edge', 'serverless'],
  },
  'yousign': {
    name: 'YouSign',
    type: 'statuspage',
    pageUrl: 'https://yousign.statuspage.io',
    apiBase: 'https://yousign.statuspage.io/api/v2',
    relatedDomains: ['yousign.com', '*.yousign.com', 'yousign.app', '*.yousign.app'],
    searchAliases: ['e-signature', 'esign', 'signature', 'document', 'contract', 'sign'],
  },
  'zendesk': {
    name: 'Zendesk',
    type: 'zendesk',
    pageUrl: 'https://status.zendesk.com',
    apiBase: 'https://status.zendesk.com',
    relatedDomains: ['zendesk.com', '*.zendesk.com', 'zdassets.com'],
    searchAliases: ['customer support', 'helpdesk', 'tickets', 'crm', 'live chat'],
  },
  'zoho': {
    name: 'Zoho',
    type: 'site24x7',
    pageUrl: 'https://status.zoho.com',
    apiBase: 'https://status.zoho.com',
    relatedDomains: ['zoho.com', '*.zoho.com', 'zohopublic.com', '*.zohopublic.com'],
    searchAliases: ['crm', 'zoho mail', 'zoho docs', 'zoho books', 'zoho desk', 'zoho projects', 'zoho campaigns'],
  },
  'zoom': {
    name: 'Zoom',
    type: 'statuspage',
    pageUrl: 'https://status.zoom.us',
    apiBase: 'https://www.zoomstatus.com/api/v2',
    relatedDomains: ['zoom.us', '*.zoom.us'],
    searchAliases: ['video', 'conferencing', 'meetings', 'webinar', 'video call'],
  },
};
