// Built-in catalog of services.
//
// type (required):
//   "algolia"      — Algolia custom API; polls /3/public/availability.
//   "auth0"        — Auth0 custom Next.js page; extracts buildId from HTML then
//                    fetches /_next/data/{buildId}/index.json for region status.
//   "awshealth"    — AWS Service Health Dashboard; polls /public/currentevents (UTF-16 encoded).
//   "cachet"       — CachetHQ status pages; polls /components and /incidents. Supports both
//   "checkly"      — Checkly (checklyhq.com) status pages; derives component status from
//                    /api/status-page/{slug}/unresolved-incidents and uptime. Requires a
//                    `slug` field on the catalog entry.
//                    v1/v2 flat format and v3 JSON:API format (auto-detected per response).
//   "google"       — Google incident dashboard format (used by Google Workspace and Google Cloud);
//                    polls /incidents.json + /products.json and derives status from active incidents
//                    (those with no `end` field).
//   "heroku"       — Heroku custom API; polls /api/v4/current-status.
//   "hund"         — Hund.io status pages; reads the first SSE init_event from /live/v2/status_page.
//   "incidentio"   — incident.io status pages; exposes the same /api/v2 endpoints as Statuspage.io,
//                    so the same fetcher handles both.
//   "instatus"     — Instatus-hosted status pages; polls /api/v2/summary.json and
//                    /api/v2/components.json. No public incidents endpoint available.
//   "pagerduty"    — PagerDuty status page product; polls /api/services and /api/posts.
//   "posthog"      — PostHog custom Next.js status page; polls /api/status.
//   "signal"       — Signal's hand-rolled HTML page; no API. Scrapes text for "up and running".
//                    Beta — fragile if Signal changes their wording.
//   "site24x7"     — StatusIQ (Zoho/Site24x7); polls /sp/api/u/summary_details.
//   "slack"        — Slack's custom status API at /api/v1.0.0/current.
//   "sorryapp"     — SorryApp platform; polls /api/v1/status, /api/v1/components, /api/v1/notices.
//   "statuscast"   — StatusCast platform; polls /status.json, /components.json, /incidents.json.
//                    Requires a browser User-Agent (bot filter).
//   "statusio"     — status.io pages; single endpoint at api.status.io/1.0/status/{pageId}.
//                    Requires a `pageId` field on the catalog entry.
//   "statuspage"   — Atlassian Statuspage.io, uses /api/v2 endpoints.
//   "stripe"       — Stripe custom status page; polls /current/full.
//   "uptimerobot"  — UptimeRobot status pages; uses /api/getMonitorList/x.
//   "zendesk"      — Zendesk custom JSON:API; polls /api/ssp/services.json and
//                    /api/ssp/incidents.json?as_of_date={date}.
//
// searchAliases: additional keywords matched when the user types in the catalog search box.
//   Use this for well-known product names that aren't part of the service name
//   (e.g. "jira", "gmail", "chatgpt"). All lowercase; matched as substrings.
//
// relatedDomains: product/app domains for this service.
//   Patterns starting with "*." match that domain and all its subdomains.
//   Used to suggest adding a service when the user visits a related page
//   (e.g. visiting claude.ai suggests tracking status.claude.com).
//
// Intentionally excluded from wildcards: user-content hosts such as
//   *.github.io, *.vercel.app, *.netlify.app, *.myshopify.com, *.onrender.com
const CATALOG = {
  '1password': {
    name: '1Password',
    type: 'statuspage',
    websiteUrl: 'https://1password.com',
    statusPageUrl: 'https://status.1password.com',
    relatedDomains: ['1password.com', '*.1password.com'],
    searchAliases: ['password manager', 'secrets', 'vault', 'security'],
  },
  'ably': {
    name: 'Ably',
    type: 'statuspage',
    websiteUrl: 'https://ably.com',
    statusPageUrl: 'https://status.ably.com',
    relatedDomains: ['ably.com', '*.ably.com', 'ably.io', '*.ably.io'],
    searchAliases: ['realtime', 'websocket', 'pubsub', 'messaging', 'push notifications'],
  },
  'airbyte': {
    name: 'Airbyte',
    type: 'instatus',
    websiteUrl: 'https://airbyte.com',
    statusPageUrl: 'https://status.airbyte.com',
    relatedDomains: ['airbyte.com', '*.airbyte.com'],
    searchAliases: ['etl', 'data pipeline', 'data integration', 'connector', 'sync'],
  },
  'airtable': {
    name: 'Airtable',
    type: 'statuspage',
    websiteUrl: 'https://airtable.com',
    statusPageUrl: 'https://status.airtable.com',
    relatedDomains: ['airtable.com', '*.airtable.com'],
    searchAliases: ['database', 'spreadsheet', 'no-code', 'base', 'grid'],
  },
  'alchemy': {
    name: 'Alchemy',
    type: 'statuspage',
    websiteUrl: 'https://alchemy.com',
    statusPageUrl: 'https://status.alchemy.com',
    relatedDomains: ['alchemy.com', '*.alchemy.com'],
    searchAliases: ['web3', 'blockchain', 'ethereum', 'polygon', 'solana', 'nft', 'smart contracts', 'rpc'],
  },
  'algolia': {
    name: 'Algolia',
    type: 'algolia',
    websiteUrl: 'https://algolia.com',
    statusPageUrl: 'https://status.algolia.com',
    relatedDomains: ['algolia.com', '*.algolia.com', 'algolia.net', '*.algolia.net'],
    searchAliases: ['search', 'autocomplete', 'instant search', 'indexing'],
  },
  'apify': {
    name: 'Apify',
    type: 'statuspage',
    websiteUrl: 'https://apify.com',
    statusPageUrl: 'https://status.apify.com',
    relatedDomains: ['apify.com', '*.apify.com'],
    searchAliases: ['scraping', 'web scraper', 'crawler', 'automation', 'actor', 'proxy'],
  },
  'atlassian': {
    name: 'Atlassian',
    type: 'statuspage',
    websiteUrl: 'https://atlassian.com',
    statusPageUrl: 'https://status.atlassian.com',
    relatedDomains: [
      'atlassian.com', '*.atlassian.com',
      'atlassian.net', '*.atlassian.net',
      'jira.com', '*.jira.com',
      'trello.com', '*.trello.com',
      'confluence.com',
    ],
    searchAliases: ['jira', 'confluence', 'trello', 'bitbucket', 'opsgenie', 'statuspage', 'loom', 'issues', 'project management'],
  },
  'auth0': {
    name: 'Auth0',
    type: 'auth0',
    websiteUrl: 'https://auth0.com',
    statusPageUrl: 'https://status.auth0.com',
    relatedDomains: ['auth0.com', '*.auth0.com', 'okta.com', '*.okta.com'],
    searchAliases: ['okta', 'authentication', 'identity', 'login', 'sso', 'oauth'],
  },
  'aws': {
    name: 'AWS',
    type: 'awshealth',
    beta: true,
    websiteUrl: 'https://aws.amazon.com',
    statusPageUrl: 'https://health.aws.com/health/status',
    relatedDomains: ['aws.amazon.com', 'console.aws.amazon.com', 'health.aws.com'],
    searchAliases: ['amazon', 'amazon web services', 'ec2', 's3', 'lambda', 'rds', 'cloudfront', 'dynamodb', 'eks', 'ecs', 'cloudwatch'],
  },
  'axiom': {
    name: 'Axiom',
    type: 'statuspage',
    websiteUrl: 'https://axiom.co',
    statusPageUrl: 'https://axiomdev.statuspage.io',
    relatedDomains: ['axiom.co', '*.axiom.co'],
    searchAliases: ['logs', 'log analytics', 'observability', 'tracing', 'events', 'monitoring'],
  },
  'bitwarden': {
    name: 'Bitwarden',
    type: 'hund',
    websiteUrl: 'https://bitwarden.com',
    statusPageUrl: 'https://status.bitwarden.com',
    relatedDomains: ['bitwarden.com', '*.bitwarden.com'],
    searchAliases: ['password manager', 'passwords', 'vault', 'security'],
  },
  'brex': {
    name: 'Brex',
    type: 'statuspage',
    websiteUrl: 'https://brex.com',
    statusPageUrl: 'https://status.brex.com',
    relatedDomains: ['brex.com', '*.brex.com'],
    searchAliases: ['fintech', 'corporate card', 'spend management', 'banking', 'finance'],
  },
  'buildkite': {
    name: 'Buildkite',
    type: 'statuspage',
    websiteUrl: 'https://buildkite.com',
    statusPageUrl: 'https://www.buildkitestatus.com',
    relatedDomains: ['buildkite.com', '*.buildkite.com'],
    searchAliases: ['ci', 'cd', 'ci/cd', 'continuous integration', 'pipeline', 'build', 'agents'],
  },
  'circleci': {
    name: 'CircleCI',
    type: 'statuspage',
    websiteUrl: 'https://circleci.com',
    statusPageUrl: 'https://status.circleci.com',
    relatedDomains: ['circleci.com', '*.circleci.com'],
    searchAliases: ['ci', 'cd', 'ci/cd', 'continuous integration', 'pipeline', 'build'],
  },
  'claude': {
    name: 'Claude',
    type: 'statuspage',
    websiteUrl: 'https://claude.ai',
    statusPageUrl: 'https://status.claude.com',
    relatedDomains: ['claude.ai', '*.claude.ai', 'anthropic.com', '*.anthropic.com'],
    searchAliases: ['anthropic', 'ai', 'llm', 'chatbot'],
  },
  'clerk': {
    name: 'Clerk',
    type: 'statuspage',
    websiteUrl: 'https://clerk.com',
    statusPageUrl: 'https://status.clerk.com',
    relatedDomains: ['clerk.com', '*.clerk.com', 'clerk.dev', '*.clerk.dev', 'clerk.accounts.dev'],
    searchAliases: ['authentication', 'auth', 'login', 'user management', 'identity', 'session'],
  },
  'clever-cloud': {
    name: 'Clever Cloud',
    type: 'cachet',
    beta: true,
    websiteUrl: 'https://clever-cloud.com',
    statusPageUrl: 'https://www.clevercloudstatus.com',
    relatedDomains: ['clever-cloud.com', '*.clever-cloud.com'],
    searchAliases: ['paas', 'cloud', 'hosting', 'deployment', 'scaleway'],
  },
  'cloudflare': {
    name: 'Cloudflare',
    type: 'statuspage',
    websiteUrl: 'https://cloudflare.com',
    statusPageUrl: 'https://www.cloudflarestatus.com',
    relatedDomains: ['cloudflare.com', '*.cloudflare.com'],
    searchAliases: ['cdn', 'dns', 'workers', 'pages', 'waf', 'ddos', 'tunnel', 'r2'],
  },
  'cloudinary': {
    name: 'Cloudinary',
    type: 'statuspage',
    websiteUrl: 'https://cloudinary.com',
    statusPageUrl: 'https://status.cloudinary.com',
    relatedDomains: ['cloudinary.com', '*.cloudinary.com'],
    searchAliases: ['images', 'media', 'cdn', 'video', 'image optimization', 'upload'],
  },
  'cloudsmith': {
    name: 'Cloudsmith',
    type: 'statuspage',
    websiteUrl: 'https://cloudsmith.com',
    statusPageUrl: 'https://status.cloudsmith.com',
    relatedDomains: ['cloudsmith.com', '*.cloudsmith.com', 'cloudsmith.io', '*.cloudsmith.io'],
    searchAliases: ['package registry', 'artifact', 'npm', 'docker', 'maven', 'pypi', 'repository'],
  },
  'cohere': {
    name: 'Cohere',
    type: 'statuspage',
    websiteUrl: 'https://cohere.com',
    statusPageUrl: 'https://status.cohere.com',
    relatedDomains: ['cohere.com', '*.cohere.com', 'cohere.ai', '*.cohere.ai'],
    searchAliases: ['ai', 'llm', 'nlp', 'embeddings', 'language model', 'text generation'],
  },
  'configcat': {
    name: 'ConfigCat',
    type: 'site24x7',
    websiteUrl: 'https://configcat.com',
    statusPageUrl: 'https://status.configcat.com',
    relatedDomains: ['configcat.com', '*.configcat.com'],
    searchAliases: ['feature flags', 'feature toggles', 'feature management', 'a/b testing'],
  },
  'contentful': {
    name: 'Contentful',
    type: 'statuspage',
    websiteUrl: 'https://contentful.com',
    statusPageUrl: 'https://www.contentfulstatus.com',
    relatedDomains: ['contentful.com', '*.contentful.com'],
    searchAliases: ['cms', 'headless cms', 'content management', 'content api', 'rich text'],
  },
  'courier': {
    name: 'Courier',
    type: 'statuspage',
    websiteUrl: 'https://courier.com',
    statusPageUrl: 'https://status.courier.com',
    relatedDomains: ['courier.com', '*.courier.com', 'trycourier.com', '*.trycourier.com'],
    searchAliases: ['notifications', 'email', 'sms', 'push', 'in-app', 'messaging'],
  },
  'cursor': {
    name: 'Cursor',
    type: 'statuspage',
    websiteUrl: 'https://cursor.com',
    statusPageUrl: 'https://status.cursor.com',
    relatedDomains: ['cursor.com', '*.cursor.com'],
    searchAliases: ['ide', 'code editor', 'ai coding', 'copilot'],
  },
  'dashdoc': {
    name: 'Dashdoc',
    type: 'incidentio',
    websiteUrl: 'https://dashdoc.eu',
    statusPageUrl: 'https://www.dashdocstatus.com',
    relatedDomains: ['dashdoc.eu', '*.dashdoc.eu', 'dashdoc.com', '*.dashdoc.com'],
    searchAliases: ['transport', 'tms', 'logistics', 'freight', 'trucking'],
  },
  'dashlane': {
    name: 'Dashlane',
    type: 'statusio',
    websiteUrl: 'https://dashlane.com',
    statusPageUrl: 'https://status.dashlane.com',
    pageId:  '5aabcb89fccc4b04d3774443',
    relatedDomains: ['dashlane.com', '*.dashlane.com'],
    searchAliases: ['password manager', 'passwords', 'vault', 'security'],
  },
  'datadog': {
    name: 'Datadog',
    type: 'statuspage',
    websiteUrl: 'https://datadoghq.com',
    statusPageUrl: 'https://status.datadoghq.com',
    relatedDomains: ['datadoghq.com', '*.datadoghq.com'],
    searchAliases: ['monitoring', 'apm', 'logs', 'observability', 'metrics', 'infrastructure'],
  },
  'deno': {
    name: 'Deno',
    type: 'instatus',
    websiteUrl: 'https://deno.com',
    statusPageUrl: 'https://denostatus.com',
    relatedDomains: ['deno.com', '*.deno.com', 'deno.land', '*.deno.land', 'deno.dev', '*.deno.dev'],
    searchAliases: ['javascript', 'typescript', 'runtime', 'deploy', 'edge', 'serverless'],
  },
  'digitalocean': {
    name: 'DigitalOcean',
    type: 'statuspage',
    websiteUrl: 'https://digitalocean.com',
    statusPageUrl: 'https://status.digitalocean.com',
    relatedDomains: ['digitalocean.com', '*.digitalocean.com'],
    searchAliases: ['cloud', 'droplet', 'vps', 'kubernetes', 'spaces', 'managed database'],
  },
  'discord': {
    name: 'Discord',
    type: 'statuspage',
    websiteUrl: 'https://discord.com',
    statusPageUrl: 'https://discordstatus.com',
    relatedDomains: ['discord.com', '*.discord.com', 'discordapp.com'],
    searchAliases: ['chat', 'gaming', 'community', 'voice', 'server', 'bot'],
  },
  'docker': {
    name: 'Docker',
    type: 'statusio',
    websiteUrl: 'https://docker.com',
    statusPageUrl: 'https://www.dockerstatus.com',
    pageId:  '533c6539221ae15e3f000031',
    relatedDomains: ['docker.com', '*.docker.com', 'dockerhub.com'],
    searchAliases: ['containers', 'hub', 'registry', 'dockerfile', 'compose'],
  },
  'doppler': {
    name: 'Doppler',
    type: 'statuspage',
    websiteUrl: 'https://doppler.com',
    statusPageUrl: 'https://www.dopplerstatus.com',
    relatedDomains: ['doppler.com', '*.doppler.com'],
    searchAliases: ['secrets', 'environment variables', 'env vars', 'secret management', 'configuration'],
  },
  'docusign': {
    name: 'DocuSign',
    type: 'statuspage',
    websiteUrl: 'https://docusign.com',
    statusPageUrl: 'https://status.docusign.com',
    relatedDomains: ['docusign.com', '*.docusign.com', 'docusign.net', '*.docusign.net'],
    searchAliases: ['e-signature', 'esign', 'document signing', 'contracts'],
  },
  'dropbox': {
    name: 'Dropbox',
    type: 'statuspage',
    websiteUrl: 'https://dropbox.com',
    statusPageUrl: 'https://status.dropbox.com',
    relatedDomains: ['dropbox.com', '*.dropbox.com', 'dropboxbusiness.com'],
    searchAliases: ['file storage', 'cloud storage', 'sync', 'file sharing'],
  },
  'elastic': {
    name: 'Elastic Cloud',
    type: 'statuspage',
    websiteUrl: 'https://elastic.co',
    statusPageUrl: 'https://status.elastic.co',
    relatedDomains: ['elastic.co', '*.elastic.co', 'elasticsearch.com', 'found.no'],
    searchAliases: ['elasticsearch', 'kibana', 'logstash', 'beats', 'observability', 'search', 'ecs'],
  },
  'expo': {
    name: 'Expo',
    type: 'statuspage',
    websiteUrl: 'https://expo.dev',
    statusPageUrl: 'https://status.expo.dev',
    relatedDomains: ['expo.dev', '*.expo.dev', 'expo.io', '*.expo.io'],
    searchAliases: ['react native', 'mobile', 'ios', 'android', 'eas', 'build', 'ota updates'],
  },
  'fastly': {
    name: 'Fastly',
    type: 'statuscast',
    websiteUrl: 'https://fastly.com',
    statusPageUrl: 'https://www.fastlystatus.com',
    relatedDomains: ['fastly.com', '*.fastly.com', 'fastly.net', '*.fastly.net'],
    searchAliases: ['cdn', 'edge', 'cache', 'waf', 'streaming'],
  },
  'figma': {
    name: 'Figma',
    type: 'statuspage',
    websiteUrl: 'https://figma.com',
    statusPageUrl: 'https://status.figma.com',
    relatedDomains: ['figma.com', '*.figma.com'],
    searchAliases: ['design', 'prototyping', 'ui', 'ux', 'wireframe'],
  },
  'fivetran': {
    name: 'Fivetran',
    type: 'statuspage',
    websiteUrl: 'https://fivetran.com',
    statusPageUrl: 'https://status.fivetran.com',
    relatedDomains: ['fivetran.com', '*.fivetran.com'],
    searchAliases: ['etl', 'data pipeline', 'data integration', 'connector', 'elt', 'warehouse'],
  },
  'flyio': {
    name: 'Fly.io',
    type: 'statuspage',
    websiteUrl: 'https://fly.io',
    statusPageUrl: 'https://status.flyio.net',
    relatedDomains: ['fly.io', '*.fly.io'],
    searchAliases: ['hosting', 'deployment', 'containers', 'paas'],
  },
  'github': {
    name: 'GitHub',
    type: 'statuspage',
    websiteUrl: 'https://github.com',
    statusPageUrl: 'https://www.githubstatus.com',
    relatedDomains: ['github.com', '*.github.com'],
    searchAliases: ['git', 'repos', 'actions', 'copilot', 'packages', 'pages', 'gist', 'pull request'],
  },
  'gitlab': {
    name: 'GitLab',
    type: 'statusio',
    websiteUrl: 'https://gitlab.com',
    statusPageUrl: 'https://status.gitlab.com',
    pageId:  '5b36dc6502d06804c08349f7',
    relatedDomains: ['gitlab.com', '*.gitlab.com'],
    searchAliases: ['git', 'ci/cd', 'devops', 'repos', 'pipeline', 'merge request'],
  },
  'google-cloud': {
    name: 'Google Cloud',
    type: 'google',
    websiteUrl: 'https://cloud.google.com',
    statusPageUrl: 'https://status.cloud.google.com',
    relatedDomains: [
      'cloud.google.com', 'googleapis.com', '*.googleapis.com',
      'googlecloud.com', '*.googlecloud.com',
    ],
    searchAliases: ['gcp', 'gce', 'gke', 'bigquery', 'firebase', 'compute engine', 'cloud run', 'cloud functions', 'pubsub', 'spanner', 'gemini', 'vertex ai', 'vertex', 'ai studio', 'gemini api', 'gemini code assist'],
  },
  'google-workspace': {
    name: 'Google Workspace',
    type: 'google',
    websiteUrl: 'https://workspace.google.com',
    statusPageUrl: 'https://www.google.com/appsstatus/dashboard',
    relatedDomains: [
      'workspace.google.com',
      'gmail.com', 'drive.google.com', 'docs.google.com',
      'sheets.google.com', 'slides.google.com', 'meet.google.com',
      'calendar.google.com', 'chat.google.com', 'mail.google.com',
    ],
    searchAliases: ['gmail', 'google drive', 'google docs', 'google sheets', 'google meet', 'google calendar', 'google chat', 'g suite', 'gsuite', 'google mail'],
  },
  'grafana': {
    name: 'Grafana',
    type: 'statuspage',
    websiteUrl: 'https://grafana.com',
    statusPageUrl: 'https://status.grafana.com',
    relatedDomains: ['grafana.com', '*.grafana.com', 'grafana.net', '*.grafana.net'],
    searchAliases: ['monitoring', 'dashboards', 'prometheus', 'loki', 'mimir', 'tempo', 'observability'],
  },
  'groq': {
    name: 'Groq',
    type: 'incidentio',
    websiteUrl: 'https://groq.com',
    statusPageUrl: 'https://groqstatus.com',
    relatedDomains: ['groq.com', '*.groq.com'],
    searchAliases: ['ai', 'llm', 'inference', 'llama', 'mixtral', 'whisper', 'language model'],
  },
  'harvest': {
    name: 'Harvest',
    type: 'statuspage',
    websiteUrl: 'https://harvestapp.com',
    statusPageUrl: 'https://www.harveststatus.com',
    relatedDomains: ['harvestapp.com', '*.harvestapp.com', 'getharvest.com', '*.getharvest.com'],
    searchAliases: ['time tracking', 'invoicing', 'timesheets', 'billing'],
  },
  'hashicorp': {
    name: 'HashiCorp',
    type: 'incidentio',
    websiteUrl: 'https://hashicorp.com',
    statusPageUrl: 'https://status.hashicorp.com',
    relatedDomains: ['hashicorp.com', '*.hashicorp.com', 'terraform.io', '*.terraform.io', 'vagrantup.com'],
    searchAliases: ['terraform', 'vault', 'consul', 'nomad', 'packer', 'waypoint', 'hcp', 'infrastructure as code', 'iac', 'secrets'],
  },
  'hasura': {
    name: 'Hasura',
    type: 'incidentio',
    websiteUrl: 'https://hasura.io',
    statusPageUrl: 'https://hasura-status.com',
    relatedDomains: ['hasura.io', '*.hasura.io'],
    searchAliases: ['graphql', 'database', 'api', 'postgres'],
  },
  'heroku': {
    name: 'Heroku',
    type: 'heroku',
    websiteUrl: 'https://heroku.com',
    statusPageUrl: 'https://status.heroku.com',
    relatedDomains: ['heroku.com', '*.heroku.com', 'herokuapp.com'],
    searchAliases: ['paas', 'hosting', 'deployment', 'dyno', 'salesforce'],
  },
  'honeycomb': {
    name: 'Honeycomb',
    type: 'statuspage',
    websiteUrl: 'https://honeycomb.io',
    statusPageUrl: 'https://status.honeycomb.io',
    relatedDomains: ['honeycomb.io', '*.honeycomb.io'],
    searchAliases: ['observability', 'distributed tracing', 'apm', 'debugging', 'monitoring', 'events'],
  },
  'hubspot': {
    name: 'HubSpot',
    type: 'statuspage',
    websiteUrl: 'https://hubspot.com',
    statusPageUrl: 'https://status.hubspot.com',
    relatedDomains: ['hubspot.com', '*.hubspot.com', 'hubspotusercontent.com'],
    searchAliases: ['crm', 'marketing', 'sales', 'email marketing', 'automation'],
  },
  'infura': {
    name: 'Infura',
    type: 'statuspage',
    websiteUrl: 'https://infura.io',
    statusPageUrl: 'https://status.infura.io',
    relatedDomains: ['infura.io', '*.infura.io'],
    searchAliases: ['web3', 'ethereum', 'ipfs', 'blockchain', 'rpc', 'node', 'metamask'],
  },
  'intercom': {
    name: 'Intercom',
    type: 'statuspage',
    websiteUrl: 'https://intercom.com',
    statusPageUrl: 'https://www.intercomstatus.com',
    relatedDomains: ['intercom.com', '*.intercom.com', 'intercom.io', '*.intercom.io'],
    searchAliases: ['customer support', 'chat', 'messaging', 'helpdesk', 'live chat'],
  },
  'kong': {
    name: 'Kong',
    type: 'statuspage',
    websiteUrl: 'https://konghq.com',
    statusPageUrl: 'https://kong.statuspage.io',
    relatedDomains: ['konghq.com', '*.konghq.com'],
    searchAliases: ['api gateway', 'api management', 'service mesh', 'proxy', 'plugins'],
  },
  'launchdarkly': {
    name: 'LaunchDarkly',
    type: 'statuspage',
    websiteUrl: 'https://launchdarkly.com',
    statusPageUrl: 'https://status.launchdarkly.com',
    relatedDomains: ['launchdarkly.com', '*.launchdarkly.com'],
    searchAliases: ['feature flags', 'feature toggles', 'feature management', 'a/b testing'],
  },
  'letsencrypt': {
    name: "Let's Encrypt",
    type: 'statusio',
    websiteUrl: 'https://letsencrypt.org',
    statusPageUrl: 'https://letsencrypt.status.io',
    pageId: '55957a99e800baa4470002da',
    relatedDomains: ['letsencrypt.org', '*.letsencrypt.org'],
    searchAliases: ['ssl', 'tls', 'certificate', 'acme', 'https', 'certificate authority', 'free ssl'],
  },
  'linear': {
    name: 'Linear',
    type: 'incidentio',
    websiteUrl: 'https://linear.app',
    statusPageUrl: 'https://linearstatus.com',
    relatedDomains: ['linear.app', '*.linear.app'],
    searchAliases: ['project management', 'issues', 'tickets', 'sprint', 'roadmap'],
  },
  'liveblocks': {
    name: 'Liveblocks',
    type: 'statuspage',
    websiteUrl: 'https://liveblocks.io',
    statusPageUrl: 'https://liveblocks.statuspage.io',
    relatedDomains: ['liveblocks.io', '*.liveblocks.io'],
    searchAliases: ['realtime', 'collaboration', 'multiplayer', 'presence', 'yjs', 'conflict-free'],
  },
  'loom': {
    name: 'Loom',
    type: 'statuspage',
    websiteUrl: 'https://loom.com',
    statusPageUrl: 'https://loom.status.atlassian.com',
    relatedDomains: ['loom.com', '*.loom.com'],
    searchAliases: ['video', 'screen recording', 'async video', 'screen capture'],
  },
  'mailgun': {
    name: 'Mailgun',
    type: 'statuspage',
    websiteUrl: 'https://mailgun.com',
    statusPageUrl: 'https://status.mailgun.com',
    relatedDomains: ['mailgun.com', '*.mailgun.com', 'mailgun.net', '*.mailgun.net'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email api', 'sending'],
  },
  'manageengine': {
    name: 'ManageEngine',
    type: 'site24x7',
    websiteUrl: 'https://manageengine.com',
    statusPageUrl: 'https://status.manageengine.com',
    relatedDomains: ['manageengine.com', '*.manageengine.com'],
    searchAliases: ['it management', 'helpdesk', 'service desk', 'endpoint management', 'patch management', 'ad manager'],
  },
  'mastodon': {
    name: 'Mastodon Social',
    type: 'instatus',
    websiteUrl: 'https://mastodon.social',
    statusPageUrl: 'https://status.mastodon.social',
    relatedDomains: ['mastodon.social', '*.mastodon.social'],
    searchAliases: ['fediverse', 'activitypub', 'microblogging', 'social media'],
  },
  'metabase': {
    name: 'Metabase',
    type: 'statuspage',
    websiteUrl: 'https://metabase.com',
    statusPageUrl: 'https://status.metabase.com',
    relatedDomains: ['metabase.com', '*.metabase.com'],
    searchAliases: ['business intelligence', 'bi', 'analytics', 'dashboards', 'data visualization'],
  },
  'mistral': {
    name: 'Mistral AI',
    type: 'checkly',
    websiteUrl: 'https://mistral.ai',
    statusPageUrl: 'https://status.mistral.ai',
    slug: 'mistral-ai',
    relatedDomains: ['mistral.ai', '*.mistral.ai'],
    searchAliases: ['ai', 'llm', 'language model', 'inference', 'mistral'],
  },
  'miro': {
    name: 'Miro',
    type: 'incidentio',
    websiteUrl: 'https://miro.com',
    statusPageUrl: 'https://status.miro.com',
    relatedDomains: ['miro.com', '*.miro.com'],
    searchAliases: ['whiteboard', 'collaboration', 'design', 'mind map', 'brainstorming'],
  },
  'mixpanel': {
    name: 'Mixpanel',
    type: 'statuspage',
    websiteUrl: 'https://mixpanel.com',
    statusPageUrl: 'https://www.mixpanelstatus.com',
    relatedDomains: ['mixpanel.com', '*.mixpanel.com'],
    searchAliases: ['analytics', 'product analytics', 'events', 'funnel', 'retention'],
  },
  'mongodb': {
    name: 'MongoDB Atlas',
    type: 'statuspage',
    websiteUrl: 'https://mongodb.com',
    statusPageUrl: 'https://status.mongodb.com',
    relatedDomains: ['mongodb.com', '*.mongodb.com', 'mongodb.net', '*.mongodb.net'],
    searchAliases: ['mongodb', 'database', 'nosql', 'atlas', 'document store'],
  },
  'mux': {
    name: 'Mux',
    type: 'statuspage',
    websiteUrl: 'https://mux.com',
    statusPageUrl: 'https://status.mux.com',
    relatedDomains: ['mux.com', '*.mux.com'],
    searchAliases: ['video', 'video api', 'live streaming', 'video hosting', 'hls', 'player'],
  },
  'n8n': {
    name: 'n8n',
    type: 'statuspage',
    websiteUrl: 'https://n8n.io',
    statusPageUrl: 'https://n8n.statuspage.io',
    relatedDomains: ['n8n.io', '*.n8n.io'],
    searchAliases: ['workflow', 'automation', 'self-hosted', 'integration', 'zapier alternative', 'no-code'],
  },
  'nabucasa': {
    name: 'Nabu Casa',
    type: 'statuspage',
    websiteUrl: 'https://nabucasa.com',
    statusPageUrl: 'https://status.nabucasa.com',
    relatedDomains: ['nabucasa.com', '*.nabucasa.com'],
    searchAliases: ['home assistant', 'home assistant cloud', 'smart home', 'iot', 'hass'],
  },
  'neon': {
    name: 'Neon',
    type: 'statusio',
    websiteUrl: 'https://neon.tech',
    statusPageUrl: 'https://neonstatus.com',
    pageId:  '6878fc85709daa75be6c7e3c',
    relatedDomains: ['neon.tech', '*.neon.tech'],
    searchAliases: ['postgres', 'postgresql', 'serverless', 'database', 'branching'],
  },
  'netlify': {
    name: 'Netlify',
    type: 'statuspage',
    websiteUrl: 'https://netlify.com',
    statusPageUrl: 'https://netlifystatus.com',
    relatedDomains: ['netlify.com', '*.netlify.com'],
    searchAliases: ['hosting', 'jamstack', 'deployment', 'static site', 'frontend', 'edge functions'],
  },
  'newrelic': {
    name: 'New Relic',
    type: 'statuspage',
    websiteUrl: 'https://newrelic.com',
    statusPageUrl: 'https://status.newrelic.com',
    relatedDomains: ['newrelic.com', '*.newrelic.com'],
    searchAliases: ['monitoring', 'apm', 'observability', 'logs', 'metrics', 'tracing'],
  },
  'ngrok': {
    name: 'ngrok',
    type: 'statuspage',
    websiteUrl: 'https://ngrok.com',
    statusPageUrl: 'https://status.ngrok.com',
    relatedDomains: ['ngrok.com', '*.ngrok.com', 'ngrok.io', '*.ngrok.io'],
    searchAliases: ['tunnel', 'tunneling', 'localhost', 'webhook', 'reverse proxy', 'expose'],
  },
  'notion': {
    name: 'Notion',
    type: 'statuspage',
    websiteUrl: 'https://notion.so',
    statusPageUrl: 'https://www.notion-status.com',
    relatedDomains: ['notion.so', '*.notion.so', 'notion.com', '*.notion.com'],
    searchAliases: ['notes', 'wiki', 'docs', 'workspace', 'knowledge base', 'database'],
  },
  'npm': {
    name: 'npm',
    type: 'statuspage',
    websiteUrl: 'https://npmjs.com',
    statusPageUrl: 'https://status.npmjs.org',
    relatedDomains: ['npmjs.com', 'npmjs.org', 'npm.com'],
    searchAliases: ['node', 'nodejs', 'package manager', 'registry', 'javascript', 'packages'],
  },
  'openai': {
    name: 'OpenAI',
    type: 'incidentio',
    websiteUrl: 'https://openai.com',
    statusPageUrl: 'https://status.openai.com',
    relatedDomains: ['openai.com', '*.openai.com', 'chatgpt.com', '*.chatgpt.com'],
    searchAliases: ['chatgpt', 'gpt', 'gpt-4', 'ai', 'llm', 'dall-e', 'whisper'],
  },
  'packagist': {
    name: 'Packagist',
    type: 'uptimerobot',
    websiteUrl: 'https://packagist.org',
    statusPageUrl: 'https://status.packagist.org',
    relatedDomains: ['packagist.org', '*.packagist.org'],
    searchAliases: ['php', 'composer', 'package manager', 'registry'],
  },
  'pagerduty': {
    name: 'PagerDuty',
    type: 'pagerduty',
    websiteUrl: 'https://pagerduty.com',
    statusPageUrl: 'https://status.pagerduty.com',
    relatedDomains: ['pagerduty.com', '*.pagerduty.com'],
    searchAliases: ['on-call', 'alerting', 'incident management', 'ops', 'devops'],
  },
  'pandadoc': {
    name: 'PandaDoc',
    type: 'statuspage',
    websiteUrl: 'https://pandadoc.com',
    statusPageUrl: 'https://status.pandadoc.com',
    relatedDomains: ['pandadoc.com', '*.pandadoc.com'],
    searchAliases: ['e-signature', 'esign', 'proposals', 'contracts', 'documents'],
  },
  'pinecone': {
    name: 'Pinecone',
    type: 'statuspage',
    websiteUrl: 'https://pinecone.io',
    statusPageUrl: 'https://status.pinecone.io',
    relatedDomains: ['pinecone.io', '*.pinecone.io'],
    searchAliases: ['vector database', 'embeddings', 'ai', 'semantic search', 'rag', 'similarity search'],
  },
  'plaid': {
    name: 'Plaid',
    type: 'statuspage',
    websiteUrl: 'https://plaid.com',
    statusPageUrl: 'https://status.plaid.com',
    relatedDomains: ['plaid.com', '*.plaid.com'],
    searchAliases: ['fintech', 'banking', 'open banking', 'financial data', 'bank connection'],
  },
  'planetscale': {
    name: 'PlanetScale',
    type: 'statuspage',
    websiteUrl: 'https://planetscale.com',
    statusPageUrl: 'https://www.planetscalestatus.com',
    relatedDomains: ['planetscale.com', '*.planetscale.com'],
    searchAliases: ['mysql', 'database', 'serverless db', 'vitess'],
  },
  'posthog': {
    name: 'PostHog',
    type: 'posthog',
    websiteUrl: 'https://posthog.com',
    statusPageUrl: 'https://www.posthogstatus.com',
    relatedDomains: ['posthog.com', '*.posthog.com'],
    searchAliases: ['analytics', 'product analytics', 'feature flags', 'session recording', 'funnels'],
  },
  'postmark': {
    name: 'Postmark',
    type: 'sorryapp',
    websiteUrl: 'https://postmarkapp.com',
    statusPageUrl: 'https://status.postmarkapp.com',
    relatedDomains: ['postmarkapp.com', '*.postmarkapp.com'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email delivery'],
  },
  'prisma': {
    name: 'Prisma',
    type: 'statuspage',
    websiteUrl: 'https://prisma.io',
    statusPageUrl: 'https://prisma.statuspage.io',
    relatedDomains: ['prisma.io', '*.prisma.io'],
    searchAliases: ['orm', 'database', 'typescript', 'postgres', 'mysql', 'mongodb', 'query builder'],
  },
  'proton': {
    name: 'Proton',
    type: 'statuspage',
    websiteUrl: 'https://proton.me',
    statusPageUrl: 'https://status.proton.me',
    relatedDomains: ['proton.me', '*.proton.me', 'protonmail.com', '*.protonmail.com', 'protonvpn.com'],
    searchAliases: ['protonmail', 'proton vpn', 'proton drive', 'email', 'privacy', 'encrypted'],
  },
  'python': {
    name: 'Python Infrastructure',
    type: 'statuspage',
    websiteUrl: 'https://python.org',
    statusPageUrl: 'https://status.python.org',
    relatedDomains: ['python.org', '*.python.org', 'pypi.org', '*.pypi.org'],
    searchAliases: ['pypi', 'pip', 'python'],
  },
  'quicknode': {
    name: 'QuickNode',
    type: 'statuspage',
    websiteUrl: 'https://quicknode.com',
    statusPageUrl: 'https://status.quicknode.com',
    relatedDomains: ['quicknode.com', '*.quicknode.com'],
    searchAliases: ['web3', 'blockchain', 'ethereum', 'solana', 'rpc', 'node', 'infrastructure'],
  },
  'replicate': {
    name: 'Replicate',
    type: 'statuspage',
    websiteUrl: 'https://replicate.com',
    statusPageUrl: 'https://www.replicatestatus.com',
    relatedDomains: ['replicate.com', '*.replicate.com'],
    searchAliases: ['ai', 'ml', 'machine learning', 'image generation', 'stable diffusion', 'models'],
  },
  'render': {
    name: 'Render',
    type: 'statuspage',
    websiteUrl: 'https://render.com',
    statusPageUrl: 'https://status.render.com',
    relatedDomains: ['render.com', '*.render.com'],
    searchAliases: ['hosting', 'paas', 'deployment', 'static site', 'cron jobs'],
  },
  'resend': {
    name: 'Resend',
    type: 'incidentio',
    websiteUrl: 'https://resend.com',
    statusPageUrl: 'https://resend-status.com',
    relatedDomains: ['resend.com', '*.resend.com'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email api'],
  },
  'retool': {
    name: 'Retool',
    type: 'statuspage',
    websiteUrl: 'https://retool.com',
    statusPageUrl: 'https://status.retool.com',
    relatedDomains: ['retool.com', '*.retool.com'],
    searchAliases: ['internal tools', 'low-code', 'no-code', 'admin panel', 'dashboard builder'],
  },
  'rollbar': {
    name: 'Rollbar',
    type: 'statuspage',
    websiteUrl: 'https://rollbar.com',
    statusPageUrl: 'https://status.rollbar.com',
    relatedDomains: ['rollbar.com', '*.rollbar.com'],
    searchAliases: ['error tracking', 'exceptions', 'crash reporting', 'monitoring', 'debugging'],
  },
  'sanity': {
    name: 'Sanity',
    type: 'statuspage',
    websiteUrl: 'https://sanity.io',
    statusPageUrl: 'https://www.sanity-status.com',
    relatedDomains: ['sanity.io', '*.sanity.io'],
    searchAliases: ['cms', 'headless cms', 'content management', 'groq', 'studio', 'content lake'],
  },
  'segment': {
    name: 'Segment',
    type: 'statuspage',
    websiteUrl: 'https://segment.com',
    statusPageUrl: 'https://status.segment.com',
    relatedDomains: ['segment.com', '*.segment.com', 'segment.io', '*.segment.io'],
    searchAliases: ['analytics', 'cdp', 'customer data', 'event tracking', 'data pipeline'],
  },
  'sendgrid': {
    name: 'SendGrid',
    type: 'statuspage',
    websiteUrl: 'https://sendgrid.com',
    statusPageUrl: 'https://status.sendgrid.com',
    relatedDomains: ['sendgrid.com', '*.sendgrid.com', 'sendgrid.net', '*.sendgrid.net'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email delivery', 'twilio'],
  },
  'sentry': {
    name: 'Sentry',
    type: 'statuspage',
    websiteUrl: 'https://sentry.io',
    statusPageUrl: 'https://status.sentry.io',
    relatedDomains: ['sentry.io', '*.sentry.io'],
    searchAliases: ['error tracking', 'monitoring', 'debugging', 'crash reporting', 'performance'],
  },
  'signal': {
    name: 'Signal',
    type: 'signal',
    beta: true,
    websiteUrl: 'https://signal.org',
    statusPageUrl: 'https://status.signal.org',
    relatedDomains: ['signal.org', '*.signal.org', 'signal.me'],
    searchAliases: ['messaging', 'encrypted', 'chat', 'private'],
  },
  'shopify': {
    name: 'Shopify',
    type: 'statuspage',
    websiteUrl: 'https://shopify.com',
    statusPageUrl: 'https://www.shopifystatus.com',
    relatedDomains: ['shopify.com', '*.shopify.com', 'shopifycloud.com'],
    searchAliases: ['ecommerce', 'e-commerce', 'shop', 'store', 'payments', 'checkout'],
  },
  'slack': {
    name: 'Slack',
    type: 'slack',
    websiteUrl: 'https://slack.com',
    statusPageUrl: 'https://slack-status.com',
    relatedDomains: ['slack.com', '*.slack.com'],
    searchAliases: ['messaging', 'chat', 'team communication', 'channels', 'workspace'],
  },
  'snowflake': {
    name: 'Snowflake',
    type: 'statuspage',
    websiteUrl: 'https://snowflake.com',
    statusPageUrl: 'https://status.snowflake.com',
    relatedDomains: ['snowflake.com', '*.snowflake.com', '*.snowflakecomputing.com'],
    searchAliases: ['data warehouse', 'cloud database', 'analytics', 'sql', 'data sharing'],
  },
  'sparkpost': {
    name: 'SparkPost',
    type: 'statuspage',
    websiteUrl: 'https://sparkpost.com',
    statusPageUrl: 'https://status.sparkpost.com',
    relatedDomains: ['sparkpost.com', '*.sparkpost.com', 'messagesystems.com'],
    searchAliases: ['email', 'transactional email', 'smtp', 'email delivery', 'email api'],
  },
  'stripe': {
    name: 'Stripe',
    type: 'stripe',
    websiteUrl: 'https://stripe.com',
    statusPageUrl: 'https://status.stripe.com',
    relatedDomains: ['stripe.com', '*.stripe.com'],
    searchAliases: ['payments', 'billing', 'subscriptions', 'checkout', 'invoices'],
  },
  'stytch': {
    name: 'Stytch',
    type: 'instatus',
    websiteUrl: 'https://stytch.com',
    statusPageUrl: 'https://status.stytch.com',
    relatedDomains: ['stytch.com', '*.stytch.com'],
    searchAliases: ['authentication', 'auth', 'login', 'passwordless', 'magic link', 'identity'],
  },
  'supabase': {
    name: 'Supabase',
    type: 'statuspage',
    websiteUrl: 'https://supabase.com',
    statusPageUrl: 'https://status.supabase.com',
    relatedDomains: ['supabase.com', '*.supabase.com', 'supabase.io', 'supabase.co'],
    searchAliases: ['postgres', 'postgresql', 'database', 'firebase alternative', 'auth', 'storage', 'realtime'],
  },
  'tailscale': {
    name: 'Tailscale',
    type: 'statuspage',
    websiteUrl: 'https://tailscale.com',
    statusPageUrl: 'https://status.tailscale.com',
    relatedDomains: ['tailscale.com', '*.tailscale.com'],
    searchAliases: ['vpn', 'networking', 'wireguard', 'mesh network', 'zero trust'],
  },
  'temporal': {
    name: 'Temporal',
    type: 'statuspage',
    websiteUrl: 'https://temporal.io',
    statusPageUrl: 'https://status.temporal.io',
    relatedDomains: ['temporal.io', '*.temporal.io'],
    searchAliases: ['workflow', 'orchestration', 'durable execution', 'job queue', 'saga'],
  },
  'tinybird': {
    name: 'Tinybird',
    type: 'incidentio',
    websiteUrl: 'https://tinybird.co',
    statusPageUrl: 'https://status.tinybird.co',
    relatedDomains: ['tinybird.co', '*.tinybird.co'],
    searchAliases: ['analytics', 'real-time analytics', 'data api', 'clickhouse', 'sql', 'streaming'],
  },
  'travisci': {
    name: 'Travis CI',
    type: 'statuspage',
    websiteUrl: 'https://travis-ci.com',
    statusPageUrl: 'https://www.traviscistatus.com',
    relatedDomains: ['travis-ci.com', 'travis-ci.org'],
    searchAliases: ['ci', 'continuous integration', 'build', 'pipeline'],
  },
  'twilio': {
    name: 'Twilio',
    type: 'statuspage',
    websiteUrl: 'https://twilio.com',
    statusPageUrl: 'https://status.twilio.com',
    relatedDomains: ['twilio.com', '*.twilio.com'],
    searchAliases: ['sms', 'voice', 'messaging', 'phone', 'sendgrid', 'whatsapp', 'video'],
  },
  'upstash': {
    name: 'Upstash',
    type: 'statuspage',
    websiteUrl: 'https://upstash.com',
    statusPageUrl: 'https://status.upstash.com',
    relatedDomains: ['upstash.com', '*.upstash.com'],
    searchAliases: ['redis', 'kafka', 'serverless', 'database', 'cache', 'qstash'],
  },
  'vercel': {
    name: 'Vercel',
    type: 'statuspage',
    websiteUrl: 'https://vercel.com',
    statusPageUrl: 'https://www.vercel-status.com',
    relatedDomains: ['vercel.com', '*.vercel.com'],
    searchAliases: ['hosting', 'nextjs', 'next.js', 'deployment', 'frontend', 'edge', 'serverless'],
  },
  'workos': {
    name: 'WorkOS',
    type: 'statuspage',
    websiteUrl: 'https://workos.com',
    statusPageUrl: 'https://status.workos.com',
    relatedDomains: ['workos.com', '*.workos.com'],
    searchAliases: ['sso', 'saml', 'enterprise auth', 'directory sync', 'scim', 'identity', 'authentication'],
  },
  'yousign': {
    name: 'YouSign',
    type: 'statuspage',
    websiteUrl: 'https://yousign.com',
    statusPageUrl: 'https://yousign.statuspage.io',
    relatedDomains: ['yousign.com', '*.yousign.com', 'yousign.app', '*.yousign.app'],
    searchAliases: ['e-signature', 'esign', 'signature', 'document', 'contract', 'sign'],
  },
  'zapier': {
    name: 'Zapier',
    type: 'incidentio',
    websiteUrl: 'https://zapier.com',
    statusPageUrl: 'https://status.zapier.com',
    relatedDomains: ['zapier.com', '*.zapier.com'],
    searchAliases: ['automation', 'workflow', 'integration', 'zap', 'no-code'],
  },
  'zendesk': {
    name: 'Zendesk',
    type: 'zendesk',
    websiteUrl: 'https://zendesk.com',
    statusPageUrl: 'https://status.zendesk.com',
    relatedDomains: ['zendesk.com', '*.zendesk.com', 'zdassets.com'],
    searchAliases: ['customer support', 'helpdesk', 'tickets', 'crm', 'live chat'],
  },
  'zoho': {
    name: 'Zoho',
    type: 'site24x7',
    websiteUrl: 'https://zoho.com',
    statusPageUrl: 'https://status.zoho.com',
    relatedDomains: ['zoho.com', '*.zoho.com', 'zohopublic.com', '*.zohopublic.com'],
    searchAliases: ['crm', 'zoho mail', 'zoho docs', 'zoho books', 'zoho desk', 'zoho projects', 'zoho campaigns'],
  },
  'zoom': {
    name: 'Zoom',
    type: 'statuspage',
    websiteUrl: 'https://zoom.us',
    statusPageUrl: 'https://status.zoom.us',
    relatedDomains: ['zoom.us', '*.zoom.us'],
    searchAliases: ['video', 'conferencing', 'meetings', 'webinar', 'video call'],
  },
};
